// @ts-nocheck
/**
 * SETU — Supabase Database Types (Generated)
 *
 * This file is auto-generated by:
 *   npm run db:generate
 *
 * Do NOT edit manually. Run the generate script after schema changes.
 * Until generated, this placeholder keeps TypeScript happy.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      [key: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
