-- =============================================================
-- SETU Seed 01: Tool Registry
-- =============================================================

INSERT INTO tool_registry (name, slug, category, description, is_available, integration_complexity) VALUES
  ('Salesforce', 'salesforce', 'CRM', 'Enterprise CRM — leads, deals, contacts, accounts', true, 'high'),
  ('HubSpot', 'hubspot', 'CRM', 'SMB/mid-market CRM and marketing automation', true, 'medium'),
  ('Pipedrive', 'pipedrive', 'CRM', 'Sales-focused CRM with pipeline views', true, 'medium'),
  ('Gmail', 'gmail', 'Email', 'Google Workspace email', true, 'low'),
  ('Outlook', 'outlook', 'Email', 'Microsoft 365 email', true, 'low'),
  ('Resend', 'resend', 'Email', 'Transactional email API', true, 'low'),
  ('Google Calendar', 'google-calendar', 'Calendar', 'Google Workspace calendar', true, 'low'),
  ('Outlook Calendar', 'outlook-calendar', 'Calendar', 'Microsoft 365 calendar', true, 'low'),
  ('Calendly', 'calendly', 'Calendar', 'Scheduling and booking', true, 'low'),
  ('Slack', 'slack', 'Slack / Teams', 'Team messaging and notifications', true, 'low'),
  ('Microsoft Teams', 'microsoft-teams', 'Slack / Teams', 'Microsoft team collaboration', true, 'medium'),
  ('Zendesk', 'zendesk', 'Support Desk', 'Enterprise customer support ticketing', true, 'medium'),
  ('Intercom', 'intercom', 'Support Desk', 'Customer messaging and support', true, 'medium'),
  ('Freshdesk', 'freshdesk', 'Support Desk', 'SMB customer support platform', true, 'medium'),
  ('QuickBooks', 'quickbooks', 'Finance / ERP', 'SMB accounting and bookkeeping', true, 'high'),
  ('Xero', 'xero', 'Finance / ERP', 'Cloud accounting platform', true, 'high'),
  ('NetSuite', 'netsuite', 'Finance / ERP', 'Enterprise ERP and financial management', true, 'high'),
  ('Stripe', 'stripe', 'Finance / ERP', 'Payment processing and billing', true, 'medium'),
  ('Google Drive', 'google-drive', 'Documents / Drive', 'Cloud file storage and collaboration', true, 'low'),
  ('SharePoint', 'sharepoint', 'Documents / Drive', 'Microsoft document management', true, 'medium'),
  ('Notion', 'notion', 'Documents / Drive', 'Workspace and knowledge management', true, 'low'),
  ('Webhook / API', 'webhook-api', 'Internal Tools / APIs', 'Generic webhook and REST API integration', true, 'medium'),
  ('Twilio', 'twilio', 'Phone / SMS', 'SMS, voice, and messaging API', true, 'medium'),
  ('Website Forms', 'website-forms', 'Website Forms', 'Web form capture and submission', true, 'low'),
  ('Google Ads', 'google-ads', 'Ads', 'Google advertising platform', true, 'medium'),
  ('Meta Ads', 'meta-ads', 'Ads', 'Facebook and Instagram advertising', true, 'medium'),
  ('LinkedIn Ads', 'linkedin-ads', 'Ads', 'LinkedIn advertising and lead gen', true, 'medium'),
  ('Okta', 'okta', 'Identity / Security', 'Enterprise identity and access management', true, 'high'),
  ('Auth0', 'auth0', 'Identity / Security', 'Developer identity platform', true, 'medium'),
  ('BambooHR', 'bamboohr', 'HRIS', 'HR information system for SMBs', true, 'medium'),
  ('Workday', 'workday', 'HRIS', 'Enterprise HR management platform', true, 'high'),
  ('DocuSign', 'docusign', 'Contract / e-signature', 'Electronic signature and contract management', true, 'medium'),
  ('PandaDoc', 'pandadoc', 'Contract / e-signature', 'Document automation and e-signature', true, 'medium'),
  ('Confluence', 'confluence', 'Knowledge Base', 'Team knowledge and documentation', true, 'medium'),
  ('Notion KB', 'notion-kb', 'Knowledge Base', 'Notion as a knowledge base', true, 'low'),
  ('OpenAI', 'openai', 'AI / LLM', 'GPT models for reasoning and generation', true, 'low'),
  ('Anthropic Claude', 'anthropic-claude', 'AI / LLM', 'Claude models for reasoning and analysis', true, 'low'),
  ('Google Sheets', 'google-sheets', 'Documents / Drive', 'Cloud spreadsheets and data', true, 'low'),
  ('Airtable', 'airtable', 'Internal Tools / APIs', 'Flexible database and project management', true, 'low'),
  ('Gong', 'gong', 'Sales / RevOps', 'Revenue intelligence and call recording', true, 'medium'),
  ('Outreach', 'outreach', 'Sales / RevOps', 'Sales engagement platform', true, 'medium')
ON CONFLICT (slug) DO NOTHING;
