// @ts-nocheck
// ── Setu Tool Registry ───────────────────────────────────────────────────────
// Every tool a customer can connect. Logo comes from Clearbit via domain.
// authType drives the connect modal copy and how keys are sent in requests.

export type AuthType = 'api_key' | 'bearer' | 'basic' | 'oauth' | 'account_sid'

export type ToolCategory =
  | 'CRM'
  | 'Email Marketing'
  | 'Paid Ads'
  | 'Analytics'
  | 'SEO'
  | 'Social Media'
  | 'Communication'
  | 'Project Management'
  | 'Sales Outreach'
  | 'Customer Support'
  | 'Finance & Payments'
  | 'Accounting'
  | 'HR & People'
  | 'Engineering'
  | 'Data & BI'
  | 'E-commerce'
  | 'Messaging'
  | 'Design'
  | 'Content & Docs'
  | 'Marketing Automation'

export interface ToolDef {
  slug: string
  name: string
  domain: string            // Clearbit logo domain
  category: ToolCategory
  description: string       // What this tool does — injected into Claude's context
  authType: AuthType
  authLabel: string         // Label shown in connect modal
  authPlaceholder: string   // Placeholder for the key input
  authHint: string          // How to get the key (short)
  baseUrl: string           // API base URL (may contain {placeholder})
  docsUrl: string
}

export const TOOL_REGISTRY: ToolDef[] = [
  // ── CRM ──────────────────────────────────────────────────────────────────
  {
    slug: 'hubspot',
    name: 'HubSpot',
    domain: 'hubspot.com',
    category: 'CRM',
    description: 'CRM, marketing automation, sales sequences, and customer service hub. API base: https://api.hubapi.com. Key endpoints: /crm/v3/objects/contacts, /crm/v3/objects/deals, /marketing/v3/emails, /automation/v4/flows.',
    authType: 'bearer',
    authLabel: 'Private App Token',
    authPlaceholder: 'pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    authHint: 'HubSpot → Settings → Integrations → Private Apps → Create app → copy token',
    baseUrl: 'https://api.hubapi.com',
    docsUrl: 'https://developers.hubspot.com/docs/api/overview',
  },
  {
    slug: 'salesforce',
    name: 'Salesforce',
    domain: 'salesforce.com',
    category: 'CRM',
    description: 'Enterprise CRM. Accounts, contacts, opportunities, leads, campaigns. API base: https://{instance}.salesforce.com/services/data/v59.0. Use Connected App OAuth or session token.',
    authType: 'bearer',
    authLabel: 'Session Token or Connected App Token',
    authPlaceholder: '00Dxx0000000xxx!AQEAxxxxxxxxxxxxxx',
    authHint: 'Salesforce → Setup → Connected Apps → OAuth → get access_token via Postman or CLI',
    baseUrl: 'https://login.salesforce.com',
    docsUrl: 'https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest',
  },
  {
    slug: 'pipedrive',
    name: 'Pipedrive',
    domain: 'pipedrive.com',
    category: 'CRM',
    description: 'Sales-focused CRM. Deals, persons, organizations, activities, pipelines. API base: https://api.pipedrive.com/v1. Append ?api_token=KEY to every request.',
    authType: 'api_key',
    authLabel: 'API Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Pipedrive → Profile → Personal Preferences → API → copy token',
    baseUrl: 'https://api.pipedrive.com/v1',
    docsUrl: 'https://developers.pipedrive.com/docs/api/v1',
  },
  {
    slug: 'zoho-crm',
    name: 'Zoho CRM',
    domain: 'zoho.com',
    category: 'CRM',
    description: 'CRM with leads, contacts, accounts, deals, and workflows. API base: https://www.zohoapis.com/crm/v6. Uses OAuth access token in Authorization: Zoho-oauthtoken header.',
    authType: 'bearer',
    authLabel: 'OAuth Access Token',
    authPlaceholder: '1000.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Zoho API Console → Self Client → generate access token with ZohoCRM.modules.ALL scope',
    baseUrl: 'https://www.zohoapis.com/crm/v6',
    docsUrl: 'https://www.zoho.com/crm/developer/docs/api/v6/',
  },
  // ── Sales Outreach ────────────────────────────────────────────────────────
  {
    slug: 'outreach',
    name: 'Outreach',
    domain: 'outreach.io',
    category: 'Sales Outreach',
    description: 'Sales engagement platform. Sequences, tasks, emails, calls, prospects. API base: https://api.outreach.io/api/v2. Bearer token auth.',
    authType: 'bearer',
    authLabel: 'API Token',
    authPlaceholder: 'eyJhbGciOiJSUzI1NiJ9...',
    authHint: 'Outreach → Settings → Apps & Integrations → API → create token',
    baseUrl: 'https://api.outreach.io/api/v2',
    docsUrl: 'https://developer.outreach.io/api/reference',
  },
  {
    slug: 'salesloft',
    name: 'Salesloft',
    domain: 'salesloft.com',
    category: 'Sales Outreach',
    description: 'Sales engagement with cadences, emails, calls, analytics. API base: https://api.salesloft.com/v2. Bearer token in Authorization header.',
    authType: 'bearer',
    authLabel: 'API Key',
    authPlaceholder: 'slapi_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Salesloft → Settings → API Keys → Create API Key',
    baseUrl: 'https://api.salesloft.com/v2',
    docsUrl: 'https://developers.salesloft.com/api.html',
  },
  {
    slug: 'apollo',
    name: 'Apollo.io',
    domain: 'apollo.io',
    category: 'Sales Outreach',
    description: 'B2B prospecting, contact data, email sequences. API base: https://api.apollo.io/v1. API key in X-Api-Key header or request body.',
    authType: 'api_key',
    authLabel: 'API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Apollo → Settings → Integrations → API → copy key',
    baseUrl: 'https://api.apollo.io/v1',
    docsUrl: 'https://apolloio.github.io/apollo-api-docs/',
  },
  // ── Email Marketing ───────────────────────────────────────────────────────
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    domain: 'mailchimp.com',
    category: 'Email Marketing',
    description: 'Email campaigns, automations, audiences, and analytics. API base: https://{dc}.api.mailchimp.com/3.0 where dc is the last part of your API key (e.g., us21). Auth: Basic with username "apikey" and password = your API key.',
    authType: 'basic',
    authLabel: 'API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-us21',
    authHint: 'Mailchimp → Account → Extras → API keys → Create A Key',
    baseUrl: 'https://{dc}.api.mailchimp.com/3.0',
    docsUrl: 'https://mailchimp.com/developer/marketing/api/',
  },
  {
    slug: 'klaviyo',
    name: 'Klaviyo',
    domain: 'klaviyo.com',
    category: 'Email Marketing',
    description: 'Email and SMS marketing for e-commerce. Campaigns, flows, lists, segments, profiles. API base: https://a.klaviyo.com/api. Bearer token: "Klaviyo-API-Key your-key".',
    authType: 'bearer',
    authLabel: 'Private API Key',
    authPlaceholder: 'pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Klaviyo → Account → Settings → API Keys → Create Private API Key',
    baseUrl: 'https://a.klaviyo.com/api',
    docsUrl: 'https://developers.klaviyo.com/en/reference/api-overview',
  },
  {
    slug: 'customer-io',
    name: 'Customer.io',
    domain: 'customer.io',
    category: 'Email Marketing',
    description: 'Behavioral email and messaging platform. Campaigns, broadcasts, segments, people. App API base: https://api.customer.io/v1. Track API: https://track.customer.io/api/v1. Bearer auth with App API Key.',
    authType: 'bearer',
    authLabel: 'App API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Customer.io → Settings → API Credentials → App API Keys → Create Key',
    baseUrl: 'https://api.customer.io/v1',
    docsUrl: 'https://customer.io/docs/api/',
  },
  {
    slug: 'sendgrid',
    name: 'SendGrid',
    domain: 'sendgrid.com',
    category: 'Email Marketing',
    description: 'Transactional and marketing email. Campaigns, contacts, templates, suppressions. API base: https://api.sendgrid.com/v3. Bearer token auth.',
    authType: 'bearer',
    authLabel: 'API Key',
    authPlaceholder: 'SG.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'SendGrid → Settings → API Keys → Create API Key → Full Access',
    baseUrl: 'https://api.sendgrid.com/v3',
    docsUrl: 'https://www.twilio.com/docs/sendgrid/api-reference',
  },
  {
    slug: 'activecampaign',
    name: 'ActiveCampaign',
    domain: 'activecampaign.com',
    category: 'Marketing Automation',
    description: 'CRM + email automation. Contacts, lists, automations, campaigns, deals. API base: https://{account}.api-us1.com/api/3. Header: Api-Token: your-key.',
    authType: 'api_key',
    authLabel: 'API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'ActiveCampaign → Settings → Developer → API Key (also note your Account URL)',
    baseUrl: 'https://{account}.api-us1.com/api/3',
    docsUrl: 'https://developers.activecampaign.com/reference/overview',
  },
  {
    slug: 'marketo',
    name: 'Marketo',
    domain: 'marketo.com',
    category: 'Marketing Automation',
    description: 'Enterprise marketing automation. Leads, programs, smart lists, emails, campaigns. REST API base: https://{munchkin}.mktorest.com/rest/v1. OAuth client credentials.',
    authType: 'oauth',
    authLabel: 'Client ID + Client Secret',
    authPlaceholder: 'clientId:clientSecret',
    authHint: 'Marketo → Admin → LaunchPoint → Create New Service → REST API → get Client ID and Secret',
    baseUrl: 'https://{munchkin}.mktorest.com/rest/v1',
    docsUrl: 'https://developers.marketo.com/rest-api/',
  },
  // ── Paid Ads ──────────────────────────────────────────────────────────────
  {
    slug: 'google-ads',
    name: 'Google Ads',
    domain: 'google.com',
    category: 'Paid Ads',
    description: 'Search, display, shopping, and video advertising. Campaigns, ad groups, keywords, ads, extensions. Use Google Ads API with developer token + OAuth. REST base: https://googleads.googleapis.com/v17.',
    authType: 'oauth',
    authLabel: 'Developer Token + OAuth Refresh Token',
    authPlaceholder: 'developer_token:refresh_token:client_id:client_secret',
    authHint: 'Google Ads API Center → apply for developer token → OAuth2 → refresh token',
    baseUrl: 'https://googleads.googleapis.com/v17',
    docsUrl: 'https://developers.google.com/google-ads/api/docs/start',
  },
  {
    slug: 'meta-ads',
    name: 'Meta Ads',
    domain: 'meta.com',
    category: 'Paid Ads',
    description: 'Facebook and Instagram advertising. Campaigns, ad sets, ads, audiences, insights. API base: https://graph.facebook.com/v20.0. Bearer access token.',
    authType: 'bearer',
    authLabel: 'Access Token',
    authPlaceholder: 'EAAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Meta Business Suite → Settings → Business Settings → System Users → generate token with ads_management permission',
    baseUrl: 'https://graph.facebook.com/v20.0',
    docsUrl: 'https://developers.facebook.com/docs/marketing-api/overview',
  },
  {
    slug: 'linkedin-ads',
    name: 'LinkedIn Ads',
    domain: 'linkedin.com',
    category: 'Paid Ads',
    description: 'B2B advertising on LinkedIn. Sponsored content, InMail, text ads. Campaign Manager API base: https://api.linkedin.com/rest. OAuth2 bearer token.',
    authType: 'bearer',
    authLabel: 'OAuth Access Token',
    authPlaceholder: 'AQXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'LinkedIn Developer Portal → create app → OAuth 2.0 → generate token with r_ads,rw_ads,r_ads_reporting permissions',
    baseUrl: 'https://api.linkedin.com/rest',
    docsUrl: 'https://learn.microsoft.com/en-us/linkedin/marketing/',
  },
  {
    slug: 'tiktok-ads',
    name: 'TikTok Ads',
    domain: 'tiktok.com',
    category: 'Paid Ads',
    description: 'TikTok for Business advertising. Campaigns, ad groups, creatives, audiences. API base: https://business-api.tiktok.com/open_api/v1.3. Access token in header.',
    authType: 'bearer',
    authLabel: 'Access Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'TikTok for Business → Assets → Business Center → Apps → create app → generate access token',
    baseUrl: 'https://business-api.tiktok.com/open_api/v1.3',
    docsUrl: 'https://business-api.tiktok.com/portal/docs',
  },
  // ── Analytics ─────────────────────────────────────────────────────────────
  {
    slug: 'ga4',
    name: 'Google Analytics 4',
    domain: 'google.com',
    category: 'Analytics',
    description: 'Web and app analytics. Sessions, users, events, conversions, funnels. Data API base: https://analyticsdata.googleapis.com/v1beta. OAuth service account or bearer token.',
    authType: 'bearer',
    authLabel: 'Service Account JSON or OAuth Token',
    authPlaceholder: 'ya29.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Google Cloud Console → service account → grant Analytics Viewer role → generate key or use OAuth',
    baseUrl: 'https://analyticsdata.googleapis.com/v1beta',
    docsUrl: 'https://developers.google.com/analytics/devguides/reporting/data/v1',
  },
  {
    slug: 'mixpanel',
    name: 'Mixpanel',
    domain: 'mixpanel.com',
    category: 'Analytics',
    description: 'Product analytics. Events, funnels, retention, cohorts, user profiles. Export API: https://data.mixpanel.com/api/2.0. Query API: https://mixpanel.com/api/2.0. Basic auth: username=service_account, password=secret.',
    authType: 'basic',
    authLabel: 'Service Account + Secret',
    authPlaceholder: 'service_account_user:service_account_secret',
    authHint: 'Mixpanel → Settings → Organization → Service Accounts → create account and secret',
    baseUrl: 'https://mixpanel.com/api/2.0',
    docsUrl: 'https://developer.mixpanel.com/reference/overview',
  },
  {
    slug: 'amplitude',
    name: 'Amplitude',
    domain: 'amplitude.com',
    category: 'Analytics',
    description: 'Product analytics. Charts, funnels, retention, cohorts, user behavior. Dashboard REST API base: https://amplitude.com/api/2. Header: Authorization: Basic base64(api_key:secret).',
    authType: 'basic',
    authLabel: 'API Key + Secret Key',
    authPlaceholder: 'api_key:secret_key',
    authHint: 'Amplitude → Settings → Projects → your project → API Key and Secret Key',
    baseUrl: 'https://amplitude.com/api/2',
    docsUrl: 'https://www.docs.developers.amplitude.com/analytics/apis/',
  },
  {
    slug: 'posthog',
    name: 'PostHog',
    domain: 'posthog.com',
    category: 'Analytics',
    description: 'Open-source product analytics. Events, feature flags, session recordings, funnels. API base: https://app.posthog.com/api. Personal API key as Authorization: Bearer.',
    authType: 'bearer',
    authLabel: 'Personal API Key',
    authPlaceholder: 'phx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'PostHog → Settings → Personal API Keys → Create personal API key',
    baseUrl: 'https://app.posthog.com/api',
    docsUrl: 'https://posthog.com/docs/api',
  },
  {
    slug: 'hotjar',
    name: 'Hotjar',
    domain: 'hotjar.com',
    category: 'Analytics',
    description: 'Heatmaps, session recordings, feedback surveys, funnels. API v3 base: https://api.hotjar.com/v3. Bearer token from client credentials flow.',
    authType: 'bearer',
    authLabel: 'API Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Hotjar → Settings → Sites & Organizations → API → create token',
    baseUrl: 'https://api.hotjar.com/v3',
    docsUrl: 'https://apidocs.hotjar.com/',
  },
  // ── SEO ───────────────────────────────────────────────────────────────────
  {
    slug: 'semrush',
    name: 'Semrush',
    domain: 'semrush.com',
    category: 'SEO',
    description: 'SEO, keyword research, competitor analysis, backlinks. API base: https://api.semrush.com. Pass key as ?key= query param. Reports: domain_organic, phrase_all, backlinks.',
    authType: 'api_key',
    authLabel: 'API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Semrush → Profile → Subscription Info → API Units → copy key',
    baseUrl: 'https://api.semrush.com',
    docsUrl: 'https://developer.semrush.com/api/',
  },
  {
    slug: 'ahrefs',
    name: 'Ahrefs',
    domain: 'ahrefs.com',
    category: 'SEO',
    description: 'Backlink analysis, keyword research, site audit, rank tracking. API v3 base: https://api.ahrefs.com/v3. Bearer token in Authorization header.',
    authType: 'bearer',
    authLabel: 'API Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Ahrefs → Account Settings → API Key → generate token',
    baseUrl: 'https://api.ahrefs.com/v3',
    docsUrl: 'https://ahrefs.com/api',
  },
  {
    slug: 'search-console',
    name: 'Google Search Console',
    domain: 'google.com',
    category: 'SEO',
    description: 'Organic search performance. Queries, pages, impressions, clicks, CTR, position. API base: https://searchconsole.googleapis.com/webmasters/v3. OAuth or service account.',
    authType: 'bearer',
    authLabel: 'OAuth Token',
    authPlaceholder: 'ya29.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Google Cloud Console → service account → Search Console → grant permission → generate OAuth token',
    baseUrl: 'https://searchconsole.googleapis.com/webmasters/v3',
    docsUrl: 'https://developers.google.com/webmaster-tools/v1/api_reference_index',
  },
  // ── Social Media ──────────────────────────────────────────────────────────
  {
    slug: 'buffer',
    name: 'Buffer',
    domain: 'buffer.com',
    category: 'Social Media',
    description: 'Social media scheduling across Twitter, LinkedIn, Facebook, Instagram. API base: https://api.bufferapp.com/1. Bearer access token.',
    authType: 'bearer',
    authLabel: 'Access Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Buffer → Developer Hub → create app → OAuth2 → copy access_token',
    baseUrl: 'https://api.bufferapp.com/1',
    docsUrl: 'https://buffer.com/developers/api',
  },
  {
    slug: 'hootsuite',
    name: 'Hootsuite',
    domain: 'hootsuite.com',
    category: 'Social Media',
    description: 'Social media management, scheduling, monitoring, analytics. API base: https://platform.hootsuite.com/v1. OAuth2 bearer token.',
    authType: 'bearer',
    authLabel: 'Access Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Hootsuite → My Profile → Developer → create app → OAuth2 → access token',
    baseUrl: 'https://platform.hootsuite.com/v1',
    docsUrl: 'https://developer.hootsuite.com/',
  },
  // ── Communication ─────────────────────────────────────────────────────────
  {
    slug: 'slack',
    name: 'Slack',
    domain: 'slack.com',
    category: 'Communication',
    description: 'Team messaging. Post messages, create channels, manage users, search messages. API base: https://slack.com/api. Bearer bot token in Authorization header.',
    authType: 'bearer',
    authLabel: 'Bot Token',
    authPlaceholder: 'xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Slack API → create app → OAuth & Permissions → add scopes → Install to workspace → copy Bot User OAuth Token',
    baseUrl: 'https://slack.com/api',
    docsUrl: 'https://api.slack.com/methods',
  },
  {
    slug: 'intercom',
    name: 'Intercom',
    domain: 'intercom.com',
    category: 'Customer Support',
    description: 'Customer messaging, support, and CRM. Conversations, contacts, companies, tickets. API base: https://api.intercom.io. Bearer token auth.',
    authType: 'bearer',
    authLabel: 'Access Token',
    authPlaceholder: 'dG9rOjxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Intercom → Settings → Developers → Your apps → create app → Access Token',
    baseUrl: 'https://api.intercom.io',
    docsUrl: 'https://developers.intercom.com/docs/build-an-integration/learn-more/rest-apis/',
  },
  {
    slug: 'zendesk',
    name: 'Zendesk',
    domain: 'zendesk.com',
    category: 'Customer Support',
    description: 'Help desk and ticketing. Tickets, users, organizations, macros, reports. API base: https://{subdomain}.zendesk.com/api/v2. Basic auth with email:token.',
    authType: 'basic',
    authLabel: 'Email/token (email:api_token)',
    authPlaceholder: 'you@company.com/token:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Zendesk → Admin → Apps and integrations → APIs → Zendesk API → Enable → Add API Token',
    baseUrl: 'https://{subdomain}.zendesk.com/api/v2',
    docsUrl: 'https://developer.zendesk.com/api-reference/',
  },
  {
    slug: 'freshdesk',
    name: 'Freshdesk',
    domain: 'freshdesk.com',
    category: 'Customer Support',
    description: 'Help desk. Tickets, contacts, agents, groups, canned responses. API base: https://{domain}.freshdesk.com/api/v2. Basic auth with API key as username and X as password.',
    authType: 'basic',
    authLabel: 'API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Freshdesk → Profile Settings → API Key → View API Key',
    baseUrl: 'https://{domain}.freshdesk.com/api/v2',
    docsUrl: 'https://developers.freshdesk.com/api/',
  },
  {
    slug: 'twilio',
    name: 'Twilio',
    domain: 'twilio.com',
    category: 'Messaging',
    description: 'SMS, voice, WhatsApp, and email via API. Messages, calls, phone numbers. API base: https://api.twilio.com/2010-04-01. Basic auth with Account SID as username and Auth Token as password.',
    authType: 'account_sid',
    authLabel: 'Account SID + Auth Token',
    authPlaceholder: 'ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Twilio Console → Account Info → copy Account SID and Auth Token (format: SID:token)',
    baseUrl: 'https://api.twilio.com/2010-04-01',
    docsUrl: 'https://www.twilio.com/docs/usage/api',
  },
  // ── Project Management ────────────────────────────────────────────────────
  {
    slug: 'asana',
    name: 'Asana',
    domain: 'asana.com',
    category: 'Project Management',
    description: 'Task and project management. Projects, tasks, sections, teams, users, portfolios. API base: https://app.asana.com/api/1.0. Bearer personal access token.',
    authType: 'bearer',
    authLabel: 'Personal Access Token',
    authPlaceholder: '1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Asana → My Settings → Apps → Manage Developer Apps → Personal Access Tokens → New token',
    baseUrl: 'https://app.asana.com/api/1.0',
    docsUrl: 'https://developers.asana.com/docs',
  },
  {
    slug: 'jira',
    name: 'Jira',
    domain: 'atlassian.com',
    category: 'Project Management',
    description: 'Issue and project tracking. Issues, sprints, boards, epics, projects. API base: https://{domain}.atlassian.net/rest/api/3. Basic auth with email:api_token.',
    authType: 'basic',
    authLabel: 'Email + API Token',
    authPlaceholder: 'email@company.com:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Atlassian → id.atlassian.com → Security → Create and manage API tokens',
    baseUrl: 'https://{domain}.atlassian.net/rest/api/3',
    docsUrl: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3/',
  },
  {
    slug: 'notion',
    name: 'Notion',
    domain: 'notion.so',
    category: 'Content & Docs',
    description: 'Docs, databases, wikis, tasks. Pages, databases, blocks, comments. API base: https://api.notion.com/v1. Bearer integration token.',
    authType: 'bearer',
    authLabel: 'Integration Token',
    authPlaceholder: 'secret_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Notion → Settings → Connections → Develop or manage integrations → New integration → copy Internal Integration Secret',
    baseUrl: 'https://api.notion.com/v1',
    docsUrl: 'https://developers.notion.com/reference/intro',
  },
  {
    slug: 'linear',
    name: 'Linear',
    domain: 'linear.app',
    category: 'Project Management',
    description: 'Engineering issue tracker. Issues, projects, cycles, teams, workflows. GraphQL API: https://api.linear.app/graphql. Bearer API key.',
    authType: 'bearer',
    authLabel: 'API Key',
    authPlaceholder: 'lin_api_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Linear → Settings → API → Personal API Keys → Create key',
    baseUrl: 'https://api.linear.app/graphql',
    docsUrl: 'https://developers.linear.app/docs',
  },
  {
    slug: 'monday',
    name: 'Monday.com',
    domain: 'monday.com',
    category: 'Project Management',
    description: 'Work OS for projects, tasks, and workflows. Boards, items, columns, groups. GraphQL API: https://api.monday.com/v2. Bearer token.',
    authType: 'bearer',
    authLabel: 'API Token',
    authPlaceholder: 'eyJhbGciOiJIUzI1NiJ9...',
    authHint: 'Monday.com → Profile → Developers → My Access Tokens → copy token',
    baseUrl: 'https://api.monday.com/v2',
    docsUrl: 'https://developer.monday.com/api-reference/docs',
  },
  {
    slug: 'clickup',
    name: 'ClickUp',
    domain: 'clickup.com',
    category: 'Project Management',
    description: 'All-in-one project management. Tasks, lists, spaces, docs, goals. API base: https://api.clickup.com/api/v2. Bearer personal token.',
    authType: 'bearer',
    authLabel: 'Personal Token',
    authPlaceholder: 'pk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'ClickUp → Settings → Apps → API → Generate token',
    baseUrl: 'https://api.clickup.com/api/v2',
    docsUrl: 'https://clickup.com/api',
  },
  {
    slug: 'airtable',
    name: 'Airtable',
    domain: 'airtable.com',
    category: 'Content & Docs',
    description: 'Flexible database + spreadsheet. Records, fields, tables, views, automations. API base: https://api.airtable.com/v0. Bearer personal access token.',
    authType: 'bearer',
    authLabel: 'Personal Access Token',
    authPlaceholder: 'patxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Airtable → Account → Developer hub → Personal access tokens → Create token',
    baseUrl: 'https://api.airtable.com/v0',
    docsUrl: 'https://airtable.com/developers/web/api/introduction',
  },
  // ── Finance & Payments ────────────────────────────────────────────────────
  {
    slug: 'stripe',
    name: 'Stripe',
    domain: 'stripe.com',
    category: 'Finance & Payments',
    description: 'Payments, subscriptions, invoices, customers, payouts. API base: https://api.stripe.com/v1. Bearer secret key.',
    authType: 'bearer',
    authLabel: 'Secret Key',
    authPlaceholder: 'sk_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Stripe Dashboard → Developers → API keys → Secret key (use restricted key for safety)',
    baseUrl: 'https://api.stripe.com/v1',
    docsUrl: 'https://stripe.com/docs/api',
  },
  {
    slug: 'razorpay',
    name: 'Razorpay',
    domain: 'razorpay.com',
    category: 'Finance & Payments',
    description: 'Indian payments gateway. Orders, payments, refunds, payouts, subscriptions. API base: https://api.razorpay.com/v1. Basic auth with Key ID and Key Secret.',
    authType: 'basic',
    authLabel: 'Key ID + Key Secret',
    authPlaceholder: 'rzp_live_xxxxxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Razorpay Dashboard → Settings → API Keys → Generate Key',
    baseUrl: 'https://api.razorpay.com/v1',
    docsUrl: 'https://razorpay.com/docs/api/',
  },
  {
    slug: 'chargebee',
    name: 'Chargebee',
    domain: 'chargebee.com',
    category: 'Finance & Payments',
    description: 'Subscription billing and revenue management. Subscriptions, customers, invoices, plans, coupons. API base: https://{site}.chargebee.com/api/v2. Basic auth with API key as username.',
    authType: 'basic',
    authLabel: 'API Key',
    authPlaceholder: 'test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Chargebee → Settings → Configure Chargebee → API Keys → create Full-Access key',
    baseUrl: 'https://{site}.chargebee.com/api/v2',
    docsUrl: 'https://apidocs.chargebee.com/docs/api',
  },
  // ── Accounting ────────────────────────────────────────────────────────────
  {
    slug: 'quickbooks',
    name: 'QuickBooks',
    domain: 'quickbooks.com',
    category: 'Accounting',
    description: 'Accounting software. Invoices, expenses, P&L, balance sheet, reports. API base: https://quickbooks.api.intuit.com/v3. OAuth2 bearer token.',
    authType: 'oauth',
    authLabel: 'OAuth Access Token + Realm ID',
    authPlaceholder: 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0:realmId',
    authHint: 'Intuit Developer → create app → OAuth 2.0 → Sandbox or Production credentials',
    baseUrl: 'https://quickbooks.api.intuit.com/v3',
    docsUrl: 'https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account',
  },
  {
    slug: 'xero',
    name: 'Xero',
    domain: 'xero.com',
    category: 'Accounting',
    description: 'Cloud accounting. Invoices, bills, bank reconciliation, payroll, reporting. API base: https://api.xero.com/api.xro/2.0. OAuth2 bearer token.',
    authType: 'oauth',
    authLabel: 'OAuth2 Access Token',
    authPlaceholder: 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...',
    authHint: 'Xero Developer → My Apps → add app → OAuth 2.0 credentials → authorize',
    baseUrl: 'https://api.xero.com/api.xro/2.0',
    docsUrl: 'https://developer.xero.com/documentation/api/api-overview',
  },
  // ── HR & People ───────────────────────────────────────────────────────────
  {
    slug: 'bamboohr',
    name: 'BambooHR',
    domain: 'bamboohr.com',
    category: 'HR & People',
    description: 'HR information system. Employees, time-off, onboarding, performance, org chart. API base: https://api.bamboohr.com/api/gateway.php/{company}/v1. Basic auth with API key as username.',
    authType: 'basic',
    authLabel: 'API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'BambooHR → Account → API Keys → Add New Key',
    baseUrl: 'https://api.bamboohr.com/api/gateway.php/{company}/v1',
    docsUrl: 'https://documentation.bamboohr.com/reference/getting-started',
  },
  {
    slug: 'rippling',
    name: 'Rippling',
    domain: 'rippling.com',
    category: 'HR & People',
    description: 'All-in-one HR, payroll, IT, and benefits. Employees, payroll, apps, devices. API base: https://api.rippling.com/platform/api. Bearer token.',
    authType: 'bearer',
    authLabel: 'API Key',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Rippling → Settings → Developers → API → Create API key',
    baseUrl: 'https://api.rippling.com/platform/api',
    docsUrl: 'https://developer.rippling.com/',
  },
  {
    slug: 'darwinbox',
    name: 'Darwinbox',
    domain: 'darwinbox.com',
    category: 'HR & People',
    description: 'HRMS for Indian and Southeast Asian enterprises. Employee lifecycle, payroll, attendance, performance. API base: https://api.darwinbox.io. Bearer token.',
    authType: 'bearer',
    authLabel: 'API Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Darwinbox → Developer Settings → API Access → generate token',
    baseUrl: 'https://api.darwinbox.io',
    docsUrl: 'https://darwinbox.com/developer',
  },
  // ── Engineering ───────────────────────────────────────────────────────────
  {
    slug: 'github',
    name: 'GitHub',
    domain: 'github.com',
    category: 'Engineering',
    description: 'Source control, issues, PRs, actions, releases, projects. API base: https://api.github.com. Bearer personal access token (classic or fine-grained).',
    authType: 'bearer',
    authLabel: 'Personal Access Token',
    authPlaceholder: 'ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'GitHub → Settings → Developer settings → Personal access tokens → Fine-grained tokens → Generate new token',
    baseUrl: 'https://api.github.com',
    docsUrl: 'https://docs.github.com/en/rest',
  },
  {
    slug: 'sentry',
    name: 'Sentry',
    domain: 'sentry.io',
    category: 'Engineering',
    description: 'Error tracking and performance monitoring. Issues, events, releases, projects. API base: https://sentry.io/api/0. Bearer auth token.',
    authType: 'bearer',
    authLabel: 'Auth Token',
    authPlaceholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Sentry → User Settings → Auth Tokens → Create New Token',
    baseUrl: 'https://sentry.io/api/0',
    docsUrl: 'https://docs.sentry.io/api/',
  },
  {
    slug: 'datadog',
    name: 'Datadog',
    domain: 'datadoghq.com',
    category: 'Engineering',
    description: 'Infrastructure monitoring, APM, logs, dashboards. API base: https://api.datadoghq.com/api/v2. DD-API-KEY and DD-APPLICATION-KEY headers.',
    authType: 'api_key',
    authLabel: 'API Key + Application Key',
    authPlaceholder: 'api_key:app_key',
    authHint: 'Datadog → Organization Settings → API Keys + Application Keys → create both',
    baseUrl: 'https://api.datadoghq.com/api/v2',
    docsUrl: 'https://docs.datadoghq.com/api/latest/',
  },
  // ── Data & BI ─────────────────────────────────────────────────────────────
  {
    slug: 'tableau',
    name: 'Tableau',
    domain: 'tableau.com',
    category: 'Data & BI',
    description: 'Business intelligence and data visualization. Workbooks, views, datasources, users, sites. REST API base: https://{server}/api/3.21. Bearer token from sign-in.',
    authType: 'bearer',
    authLabel: 'Personal Access Token',
    authPlaceholder: 'name:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Tableau → My Account Settings → Personal Access Tokens → Create new token',
    baseUrl: 'https://{server}/api/3.21',
    docsUrl: 'https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm',
  },
  {
    slug: 'looker',
    name: 'Looker',
    domain: 'looker.com',
    category: 'Data & BI',
    description: 'BI and data platform. Looks, dashboards, explores, models, schedules. API base: https://{host}:19999/api/4.0. OAuth2 client credentials.',
    authType: 'oauth',
    authLabel: 'Client ID + Client Secret',
    authPlaceholder: 'client_id:client_secret',
    authHint: 'Looker → Admin → Users → API Keys → Edit your user → New API3 Key',
    baseUrl: 'https://{host}:19999/api/4.0',
    docsUrl: 'https://developers.looker.com/api/explorer/4.0/methods',
  },
  // ── E-commerce ────────────────────────────────────────────────────────────
  {
    slug: 'shopify',
    name: 'Shopify',
    domain: 'shopify.com',
    category: 'E-commerce',
    description: 'E-commerce platform. Products, orders, customers, inventory, discounts, analytics. Admin API base: https://{store}.myshopify.com/admin/api/2024-10. Bearer access token.',
    authType: 'bearer',
    authLabel: 'Admin API Access Token',
    authPlaceholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Shopify Admin → Settings → Apps → Develop apps → create app → API credentials → Admin API access token',
    baseUrl: 'https://{store}.myshopify.com/admin/api/2024-10',
    docsUrl: 'https://shopify.dev/docs/api/admin-rest',
  },
  {
    slug: 'woocommerce',
    name: 'WooCommerce',
    domain: 'woocommerce.com',
    category: 'E-commerce',
    description: 'WordPress e-commerce plugin. Products, orders, customers, coupons, reports. REST API base: https://{store}/wp-json/wc/v3. Basic auth with Consumer Key and Secret.',
    authType: 'basic',
    authLabel: 'Consumer Key + Consumer Secret',
    authPlaceholder: 'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'WooCommerce → Settings → Advanced → REST API → Add key → Read/Write permissions',
    baseUrl: 'https://{store}/wp-json/wc/v3',
    docsUrl: 'https://woocommerce.github.io/woocommerce-rest-api-docs/',
  },
  // ── Messaging ─────────────────────────────────────────────────────────────
  {
    slug: 'whatsapp-api',
    name: 'WhatsApp Business API',
    domain: 'whatsapp.com',
    category: 'Messaging',
    description: 'Programmatic WhatsApp messaging. Send templates, interactive messages, handle webhooks. Cloud API base: https://graph.facebook.com/v20.0. Bearer token with phone number ID.',
    authType: 'bearer',
    authLabel: 'Access Token',
    authPlaceholder: 'EAAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Meta for Developers → WhatsApp → Getting Started → Temporary access token or System User token',
    baseUrl: 'https://graph.facebook.com/v20.0',
    docsUrl: 'https://developers.facebook.com/docs/whatsapp/cloud-api',
  },
  {
    slug: 'moengage',
    name: 'MoEngage',
    domain: 'moengage.com',
    category: 'Marketing Automation',
    description: 'Customer engagement platform. Campaigns, push, email, SMS, in-app, analytics. API base: https://api-01.moengage.com/v1. Basic auth with App ID and Secret Key.',
    authType: 'basic',
    authLabel: 'App ID + Secret Key',
    authPlaceholder: 'APP_ID:SECRET_KEY',
    authHint: 'MoEngage → Settings → APIs → DATA API Settings → App ID and Secret Key',
    baseUrl: 'https://api-01.moengage.com/v1',
    docsUrl: 'https://developers.moengage.com/',
  },
  {
    slug: 'clevertap',
    name: 'CleverTap',
    domain: 'clevertap.com',
    category: 'Marketing Automation',
    description: 'Mobile and web engagement. Campaigns, segments, funnels, A/B testing, push notifications. API base: https://api.clevertap.com/1. X-CleverTap-Account-Id and X-CleverTap-Passcode headers.',
    authType: 'api_key',
    authLabel: 'Account ID + Passcode',
    authPlaceholder: 'ACCOUNT_ID:PASSCODE',
    authHint: 'CleverTap → Settings → CleverTap Account → Account ID and Passcode',
    baseUrl: 'https://api.clevertap.com/1',
    docsUrl: 'https://developer.clevertap.com/docs/',
  },
  // ── Design ────────────────────────────────────────────────────────────────
  {
    slug: 'canva',
    name: 'Canva',
    domain: 'canva.com',
    category: 'Design',
    description: 'Design platform. Create designs, export assets, manage brand kits, use templates. Connect API base: https://api.canva.com/rest/v1. OAuth2 bearer token.',
    authType: 'oauth',
    authLabel: 'OAuth Access Token',
    authPlaceholder: 'eyJhbGciOiJSUzI1NiJ9...',
    authHint: 'Canva Developers → create integration → OAuth2 → authorize with design:content:read write scopes',
    baseUrl: 'https://api.canva.com/rest/v1',
    docsUrl: 'https://www.canva.dev/docs/connect/',
  },
  {
    slug: 'figma',
    name: 'Figma',
    domain: 'figma.com',
    category: 'Design',
    description: 'Collaborative design tool. Files, components, frames, comments, teams. API base: https://api.figma.com/v1. Bearer personal access token.',
    authType: 'bearer',
    authLabel: 'Personal Access Token',
    authPlaceholder: 'figd_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Figma → Account Settings → Personal access tokens → Generate new token',
    baseUrl: 'https://api.figma.com/v1',
    docsUrl: 'https://www.figma.com/developers/api',
  },
  // ── Google Workspace ──────────────────────────────────────────────────────
  {
    slug: 'google-workspace',
    name: 'Google Workspace',
    domain: 'google.com',
    category: 'Content & Docs',
    description: 'Gmail, Google Docs, Sheets, Calendar, Drive. Various APIs under googleapis.com. Service account or OAuth2. Sheets API: https://sheets.googleapis.com/v4. Drive: https://www.googleapis.com/drive/v3.',
    authType: 'bearer',
    authLabel: 'OAuth2 Access Token or Service Account JSON',
    authPlaceholder: 'ya29.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    authHint: 'Google Cloud Console → Service Accounts → create → grant domain-wide delegation → generate key',
    baseUrl: 'https://www.googleapis.com',
    docsUrl: 'https://developers.google.com/workspace',
  },
  // ── Payments India ────────────────────────────────────────────────────────
  {
    slug: 'payu',
    name: 'PayU',
    domain: 'payu.in',
    category: 'Finance & Payments',
    description: 'Indian payments processing. Transactions, refunds, settlements, subscriptions. API base: https://info.payu.in. Merchant Key and Salt for HMAC auth.',
    authType: 'api_key',
    authLabel: 'Merchant Key + Salt',
    authPlaceholder: 'MERCHANT_KEY:MERCHANT_SALT',
    authHint: 'PayU Dashboard → My Account → Profile → Merchant Key and Salt',
    baseUrl: 'https://info.payu.in',
    docsUrl: 'https://devguide.payu.in/',
  },
]

// ── Lookup helpers ──────────────────────────────────────────────────────────

const REGISTRY_MAP = new Map<string, ToolDef>(
  TOOL_REGISTRY.map(t => [t.slug, t])
)

export function getTool(slug: string): ToolDef | undefined {
  return REGISTRY_MAP.get(slug)
}

export function getToolsByCategory(category: ToolCategory): ToolDef[] {
  return TOOL_REGISTRY.filter(t => t.category === category)
}

// Clearbit logo URL for a tool slug
export function toolLogoUrl(slug: string): string {
  const tool = REGISTRY_MAP.get(slug)
  if (!tool) return ''
  return `https://logo.clearbit.com/${tool.domain}`
}

// Build tool description context for Claude system prompt
export function buildToolContext(connectedSlugs: string[]): string {
  if (!connectedSlugs.length) return ''
  const lines = connectedSlugs.map(slug => {
    const t = REGISTRY_MAP.get(slug)
    if (!t) return null
    return `- **${t.name}** (${t.category}): ${t.description}`
  }).filter(Boolean)
  return lines.length
    ? `\n\nCONNECTED TOOLS:\n${lines.join('\n')}`
    : ''
}
