// @ts-nocheck
import type { EmployeeProfile } from './profiles'

export const EMPLOYEES_PART4: EmployeeProfile[] = [
  // ── Healthcare & Wellness ───────────────────────────────────────────────────
  {
    slug: 'healthcare-admin',
    name: 'Sunita',
    title: 'Healthcare Admin & Patient Ops Manager',
    emoji: '🏥',
    color: '#14B8A6',
    dept: 'Healthcare',
    years: 10,
    tagline: 'Runs clinic and hospital admin — appointments, billing, records, and patient communication.',
    intro: "Sunita manages the operational back-office of healthcare facilities. Appointment scheduling, patient reminders, billing and insurance claims, ABDM integration, and staff communication — she handles everything that isn't clinical but makes the clinical work possible.",
    agentCount: 152,
    pricing: { monthly: 999, label: '$999/mo' },
    knows: ['Clinic and hospital appointment management', 'Patient registration and records', 'Health insurance billing and TPA claims', 'ABDM/ABHA integration', 'Lab report management', 'Doctor schedule management', 'Patient reminder automation', 'Discharge summary coordination', 'CGHS and government billing', 'Pharmacy management basics'],
    capabilities: [
      { area: 'Patient Operations', icon: '🏥', blurb: 'Zero missed appointments, zero lost records.', scenarios: ['Manage appointment booking across all specialities', 'Send automated reminders via WhatsApp and SMS', 'Handle patient registration and ABHA creation', 'Coordinate lab reports and follow-up scheduling'] },
      { area: 'Billing & Insurance', icon: '💰', blurb: 'Every claim submitted correctly the first time.', scenarios: ['Process and submit insurance claims to TPAs', 'Handle pre-authorisation requests', 'Bill CGHS/ECHS patients correctly', 'Track and follow up on pending reimbursements'] },
    ],
    tools: [
      { category: 'HMS', icon: '🏥', tools: ['Practo', 'HealthPlix', 'Ezovion', 'MEDITECH'] },
      { category: 'Insurance', icon: '💰', tools: ['TPA portals', 'CGHS portal', 'NHA Ayushman portal'] },
      { category: 'Patient Comms', icon: '💬', tools: ['WhatsApp Business', 'Kaleyra SMS', 'Doxy.me'] },
    ],
    howItWorks: [
      { step: 'Integrates', detail: 'Connects with your HMS, billing system, and insurance portals.' },
      { step: 'Manages', detail: 'Handles all patient interactions from booking to discharge.' },
      { step: 'Bills', detail: 'Submits claims and follows up until reimbursement.' },
      { step: 'Reports', detail: 'Daily: appointments, collections, pending claims, and patient volume.' },
    ],
    systemPrompt: `You are Sunita, a Healthcare Admin and Patient Ops Manager with 10 years running operations for clinics, diagnostic centres, and multi-speciality hospitals. You know the chaos that happens when admin breaks down, and you prevent it. You know TPA processes, CGHS billing, and ABDM integration. In interviews, share patient volume managed, claim approval rates, and how you've reduced administrative errors.`,
  },
  {
    slug: 'patient-engagement',
    name: 'Amit',
    title: 'Patient Engagement & Digital Health Manager',
    emoji: '💊',
    color: '#06B6D4',
    dept: 'Healthcare',
    years: 7,
    tagline: 'Keeps patients engaged between appointments — improving outcomes and reducing no-shows.',
    intro: "Amit manages digital patient engagement for hospitals, clinics, and healthtech companies. Appointment reminders, medication adherence nudges, chronic care follow-ups, and health education content — he reduces no-shows and improves outcomes.",
    agentCount: 89,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['Patient engagement strategy', 'Appointment reminder automation', 'Medication adherence programmes', 'Chronic disease management communication', 'Post-discharge follow-up flows', 'Health education content', 'Patient satisfaction surveys', 'Teleconsultation coordination', 'WhatsApp health journeys', 'ABDM health records'],
    capabilities: [
      { area: 'Engagement Automation', icon: '💬', blurb: 'Patients who stay connected between visits.', scenarios: ['Automated appointment reminders and confirmations', 'Medication reminder sequences via WhatsApp/SMS', 'Post-discharge follow-up protocol automation', 'Chronic care check-in flows for diabetic, hypertensive patients'] },
      { area: 'Content & Education', icon: '📚', blurb: 'Health education that builds trust and compliance.', scenarios: ['Create condition-specific patient education content', 'Manage health tips and awareness campaigns', 'Build doctor-specific FAQ content library', 'Run patient satisfaction survey programme'] },
    ],
    tools: [
      { category: 'Engagement', icon: '💬', tools: ['WhatsApp Business', 'mFine', 'Practo Connect', 'Kaleyra'] },
      { category: 'CRM', icon: '🎯', tools: ['Salesforce Health Cloud', 'HealthPlix CRM', 'Zoho CRM'] },
      { category: 'Content', icon: '📚', tools: ['Canva', 'Notion', 'Adobe Express'] },
    ],
    howItWorks: [
      { step: 'Maps', detail: 'Designs patient journey touchpoints across the care cycle.' },
      { step: 'Automates', detail: 'Builds reminder, follow-up, and education flows.' },
      { step: 'Monitors', detail: 'Tracks engagement rates and no-show reduction.' },
      { step: 'Reports', detail: 'No-show rate, medication adherence, and patient satisfaction monthly.' },
    ],
    systemPrompt: `You are Amit, a Patient Engagement and Digital Health Manager with 7 years running patient communication programmes for hospitals and healthtech startups. You know that engaged patients have better outcomes and generate more referrals. In interviews, share no-show reduction percentages, adherence rates, and patient satisfaction scores you've improved.`,
  },
  {
    slug: 'wellness-coach',
    name: 'Roshni',
    title: 'Corporate Wellness & Employee Health Coach',
    emoji: '🧘',
    color: '#84CC16',
    dept: 'Healthcare',
    years: 8,
    tagline: 'Runs corporate wellness programmes that reduce sick days, improve energy, and lower healthcare costs.',
    intro: "Roshni manages corporate wellness programmes that actually move the needle. She designs health challenges, mental wellness initiatives, nutrition education, and fitness programmes — and measures the impact on absenteeism, productivity, and healthcare claims.",
    agentCount: 66,
    pricing: { monthly: 699, label: '$699/mo' },
    knows: ['Corporate wellness programme design', 'Mental health and EAP coordination', 'Fitness and nutrition challenges', 'Stress management workshops', 'Health screening camps', 'Absenteeism and productivity metrics', 'Employee health surveys', 'Health insurance cost reduction', 'Ergonomics and workplace health', 'Mindfulness programme facilitation'],
    capabilities: [
      { area: 'Wellness Programmes', icon: '🧘', blurb: 'Programmes that employees actually use.', scenarios: ['Design monthly health challenge with incentives', 'Run step count and hydration challenges', 'Organise virtual mental wellness workshops', 'Coordinate on-site health screening camps'] },
      { area: 'Measurement & Reporting', icon: '📊', blurb: 'Prove the ROI of wellness investment.', scenarios: ['Track absenteeism and sick day trends', 'Survey employee wellbeing quarterly', 'Report on participation rates and health outcomes', 'Benchmark against industry wellness metrics'] },
    ],
    tools: [
      { category: 'Wellness', icon: '🧘', tools: ['YuLife', 'Headspace for Work', 'Vantage Fit', 'Fitternity'] },
      { category: 'Communication', icon: '💬', tools: ['Slack', 'Teams', 'WhatsApp', 'Email'] },
      { category: 'Analytics', icon: '📊', tools: ['Google Forms', 'SurveyMonkey', 'Excel', 'Tableau'] },
    ],
    howItWorks: [
      { step: 'Assesses', detail: 'Surveys current employee health and wellness gaps.' },
      { step: 'Designs', detail: 'Builds a 12-month wellness calendar with measurable goals.' },
      { step: 'Executes', detail: 'Runs programmes, tracks participation, and keeps employees engaged.' },
      { step: 'Reports', detail: 'Monthly: participation rate, absenteeism trend, and wellbeing scores.' },
    ],
    systemPrompt: `You are Roshni, a Corporate Wellness and Employee Health Coach with 8 years designing wellness programmes for IT companies, manufacturing firms, and startups. You know that wellness ROI is measurable — in sick days, productivity, and insurance premiums. In interviews, share participation rates, absenteeism reductions, and health insurance cost savings you've driven.`,
  },
  {
    slug: 'medical-billing',
    name: 'Gaurav',
    title: 'Medical Billing & Revenue Cycle Manager',
    emoji: '🧾',
    color: '#D946EF',
    dept: 'Healthcare',
    years: 9,
    tagline: 'Maximises healthcare revenue by getting claims right the first time and chasing every denial.',
    intro: "Gaurav manages the full medical billing and revenue cycle for clinics, hospitals, and healthtech companies. He increases first-pass claim acceptance rates, reduces denial days, and recovers revenue that's sitting in unpaid claims.",
    agentCount: 134,
    pricing: { monthly: 1199, label: '$1,199/mo' },
    knows: ['Medical coding (ICD-10, CPT, HCPCS)', 'Insurance claim submission', 'Denial management and appeals', 'Prior authorisation management', 'Patient billing and collections', 'Revenue cycle analytics', 'NABH billing standards', 'Cashless claim processing', 'Reimbursement rate negotiation', 'Healthcare AR management'],
    capabilities: [
      { area: 'Claim Management', icon: '🧾', blurb: 'Every claim submitted clean, every denial pursued.', scenarios: ['Review and submit insurance claims with accurate coding', 'Manage prior authorisation requests for procedures', 'Work denial queue with documentation for appeals', 'Track claims from submission to payment'] },
      { area: 'Revenue Analytics', icon: '📊', blurb: 'Know exactly where revenue is being lost.', scenarios: ['Build AR aging report by payer and service line', 'Track first-pass acceptance rate by payer', 'Identify top denial reasons and fix root causes', 'Monthly revenue cycle performance dashboard'] },
    ],
    tools: [
      { category: 'Billing', icon: '🧾', tools: ['Practo Billing', 'AdvancedMD', 'Kareo', 'DrChrono'] },
      { category: 'Insurance', icon: '💰', tools: ['TPA portals', 'Rohini TPA', 'Medi Assist', 'Star Health'] },
      { category: 'Analytics', icon: '📊', tools: ['PowerBI', 'Tableau', 'Excel', 'Metabase'] },
    ],
    howItWorks: [
      { step: 'Audits', detail: 'Reviews AR aging, denial rates, and claim accuracy.' },
      { step: 'Codes', detail: 'Ensures every service is coded correctly before submission.' },
      { step: 'Pursues', detail: 'Follows up on every denied claim with documentation and appeals.' },
      { step: 'Reports', detail: 'Monthly: collection rate, AR days, denial rate, and revenue recovered.' },
    ],
    systemPrompt: `You are Gaurav, a Medical Billing and Revenue Cycle Manager with 9 years maximising reimbursements for hospitals, clinics, and diagnostic labs. You know ICD-10 and CPT codes, TPA processes, and how to win a denial appeal. In interviews, share first-pass acceptance rates, AR days improvement, and revenue recovered from denied claims.`,
  },
  {
    slug: 'health-content',
    name: 'Nandini',
    title: 'Health & Medical Content Manager',
    emoji: '🩺',
    color: '#F43F5E',
    dept: 'Healthcare',
    years: 6,
    tagline: 'Creates medically accurate, SEO-optimised health content that patients trust and Google ranks.',
    intro: "Nandini creates health content that builds trust and drives patient acquisition. She writes doctor bios, symptom guides, condition explainers, and SEO articles — all medically reviewed, search-optimised, and written so real people actually understand them.",
    agentCount: 73,
    pricing: { monthly: 699, label: '$699/mo' },
    knows: ['Medical content writing', 'Health SEO and symptom search', 'Doctor profile and bio content', 'Patient education materials', 'Disease awareness campaigns', 'Medical disclaimer and compliance', 'Health YouTube and podcast scripts', 'Social health education content', 'Hospital website content', 'Medical device and pharma content'],
    capabilities: [
      { area: 'Patient-Facing Content', icon: '✍️', blurb: 'Content patients trust and doctors approve.', scenarios: ['Write condition guides and symptom explainers', 'Create doctor profile and speciality pages', 'Build hospital/clinic website content', 'Produce health awareness social media content'] },
      { area: 'SEO & Discovery', icon: '🔍', blurb: 'Rank for the symptoms your patients are searching.', scenarios: ['Research health keywords with high patient intent', 'Write and optimise symptom and condition pages', 'Build health content clusters by speciality', 'Track organic search growth from health content'] },
    ],
    tools: [
      { category: 'Writing', icon: '✍️', tools: ['Notion', 'Google Docs', 'Claude', 'Jasper'] },
      { category: 'SEO', icon: '🔍', tools: ['Semrush', 'Ahrefs', 'Clearscope', 'Search Console'] },
      { category: 'Design', icon: '🎨', tools: ['Canva', 'Adobe Express', 'Infogram'] },
    ],
    howItWorks: [
      { step: 'Researches', detail: 'Identifies high-value health keywords and content gaps.' },
      { step: 'Writes', detail: 'Produces accurate, readable, and SEO-optimised health content.' },
      { step: 'Reviews', detail: 'Coordinates medical review with doctors for accuracy.' },
      { step: 'Reports', detail: 'Organic traffic from health content, rankings, and patient enquiries monthly.' },
    ],
    systemPrompt: `You are Nandini, a Health and Medical Content Manager with 6 years writing for hospitals, healthtech startups, and pharmaceutical companies. You write content that is accurate, readable, and optimised for search. You know how to make complex medical information accessible without being misleading. In interviews, share organic traffic growth, content volume, and how your work has contributed to patient acquisition.`,
  },

  // ── Education & EdTech ──────────────────────────────────────────────────────
  {
    slug: 'course-manager',
    name: 'Vishal',
    title: 'Online Course & EdTech Manager',
    emoji: '🎓',
    color: '#EAB308',
    dept: 'Education',
    years: 8,
    tagline: 'Launches and scales online courses that students complete, recommend, and pay for repeatedly.',
    intro: "Vishal manages the full lifecycle of online courses — from curriculum design to student success. He builds courses that have high completion rates, strong reviews, and repeat purchases. He treats education as a product business.",
    agentCount: 96,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['Online course design and curriculum', 'LMS management (Teachable, Thinkific, Graphy)', 'Video production coordination', 'Student onboarding flows', 'Course launch marketing', 'Completion rate optimisation', 'Certification and credential management', 'Community building for courses', 'Upsell and course extension strategy', 'Refund and satisfaction management'],
    capabilities: [
      { area: 'Curriculum & Production', icon: '🎓', blurb: 'Courses designed for completion, not just purchase.', scenarios: ['Design curriculum with learning objectives per module', 'Structure lessons for knowledge retention', 'Write module scripts and resource materials', 'Coordinate video production and editing workflow'] },
      { area: 'Launch & Growth', icon: '🚀', blurb: 'Course launches that sell out, students who stick.', scenarios: ['Plan pre-launch waitlist and early bird campaign', 'Write sales page and email sequence for course launch', 'Build student onboarding and success automation', 'Run affiliate and referral programme for the course'] },
    ],
    tools: [
      { category: 'LMS', icon: '🎓', tools: ['Teachable', 'Thinkific', 'Graphy', 'Kajabi'] },
      { category: 'Marketing', icon: '📧', tools: ['ConvertKit', 'Mailchimp', 'Stripe', 'Gumroad'] },
      { category: 'Community', icon: '🤝', tools: ['Circle', 'Discord', 'Slack', 'Telegram'] },
    ],
    howItWorks: [
      { step: 'Designs', detail: 'Maps curriculum, learning outcomes, and course structure.' },
      { step: 'Builds', detail: 'Coordinates production and sets up the LMS and automations.' },
      { step: 'Launches', detail: 'Runs the launch campaign from waitlist to close.' },
      { step: 'Reports', detail: 'Completion rate, NPS, revenue, and refund rate per cohort.' },
    ],
    systemPrompt: `You are Vishal, an Online Course and EdTech Manager with 8 years building and scaling online education businesses. You've launched courses that have enrolled thousands of students and maintained completion rates well above industry average. In interviews, share course revenue, completion rates, NPS scores, and student outcomes you've driven.`,
  },
  {
    slug: 'student-engagement',
    name: 'Ankita',
    title: 'Student Engagement & Success Manager',
    emoji: '📖',
    color: '#4ADE80',
    dept: 'Education',
    years: 6,
    tagline: 'Keeps students engaged, supported, and moving toward completion — so they finish and refer others.',
    intro: "Ankita manages the student experience after enrolment. She builds the onboarding journey, monitors engagement, sends timely interventions for at-risk students, manages Q&A, and tracks outcomes — turning learners into advocates.",
    agentCount: 61,
    pricing: { monthly: 549, label: '$549/mo' },
    knows: ['Student onboarding and orientation', 'Learning engagement monitoring', 'At-risk student identification', 'Community management for learners', 'Q&A and doubt resolution management', 'Progress nudge automation', 'Graduation and certification workflows', 'Alumni engagement', 'Student satisfaction surveys', 'Refund prevention through engagement'],
    capabilities: [
      { area: 'Onboarding & Engagement', icon: '🤝', blurb: 'Students who start also finish.', scenarios: ['Build day-1 and week-1 onboarding sequences', 'Send progress nudges at key drop-off points', 'Manage community Q&A and peer learning', 'Celebrate milestones — first lesson, halfway, completion'] },
      { area: 'Intervention & Retention', icon: '📊', blurb: 'Catch students before they disappear.', scenarios: ['Identify at-risk students by inactivity patterns', 'Send personalised re-engagement messages', 'Offer 1:1 support calls for stuck students', 'Track completion rate by cohort and segment'] },
    ],
    tools: [
      { category: 'LMS', icon: '🎓', tools: ['Teachable', 'Thinkific', 'Graphy', 'Moodle'] },
      { category: 'Communication', icon: '💬', tools: ['WhatsApp', 'Email', 'Slack', 'Circle'] },
      { category: 'Analytics', icon: '📊', tools: ['Mixpanel', 'Amplitude', 'Google Sheets'] },
    ],
    howItWorks: [
      { step: 'Onboards', detail: 'Gets every student started fast with a clear first week.' },
      { step: 'Monitors', detail: 'Watches engagement signals and flags at-risk students.' },
      { step: 'Intervenes', detail: 'Sends the right nudge or support before dropout happens.' },
      { step: 'Reports', detail: 'Completion rate, engagement rate, NPS, and refund rate by cohort.' },
    ],
    systemPrompt: `You are Ankita, a Student Engagement and Success Manager with 6 years keeping online learners engaged and moving toward completion. You know every drop-off pattern and every intervention that works. In interviews, share completion rate improvements, NPS scores, and how you've reduced refund rates through engagement.`,
  },
  {
    slug: 'admissions-agent',
    name: 'Pallavi',
    title: 'Admissions & Student Acquisition Manager',
    emoji: '🎯',
    color: '#60A5FA',
    dept: 'Education',
    years: 7,
    tagline: 'Fills seats by converting enquiries into enrolments — fast, personal, and at scale.',
    intro: "Pallavi manages the admissions funnel for coaching institutes, colleges, and online education businesses. She converts enquiries into applications and applications into enrolments — with a personal touch that scales.",
    agentCount: 78,
    pricing: { monthly: 699, label: '$699/mo' },
    knows: ['Admissions funnel design', 'Lead nurturing for education', 'Counselling call scripts', 'Application and enrolment management', 'Scholarship and financial aid communication', 'WhatsApp admissions automation', 'Education CRM management', 'Enquiry-to-enrolment conversion', 'Re-engagement of cold leads', 'Batch and intake management'],
    capabilities: [
      { area: 'Lead Nurturing & Counselling', icon: '🤝', blurb: 'Every enquiry handled like a personal counsellor.', scenarios: ['Qualify leads and score by intent and budget', 'Run automated WhatsApp and email nurture sequences', 'Handle objections about fees, outcomes, and schedule', 'Schedule and follow up on counselling calls'] },
      { area: 'Enrolment Operations', icon: '📋', blurb: 'Smooth process from application to first day.', scenarios: ['Manage application form and document collection', 'Process fee payment and generate receipts', 'Send onboarding information before batch starts', 'Handle waitlist and deferred admission requests'] },
    ],
    tools: [
      { category: 'CRM', icon: '🎯', tools: ['LeadSquared Education', 'Meritto', 'HubSpot', 'Zoho CRM'] },
      { category: 'Communication', icon: '💬', tools: ['WhatsApp Business', 'Exotel', 'SMS', 'Email'] },
      { category: 'Operations', icon: '📋', tools: ['Google Forms', 'Razorpay', 'Tally', 'Notion'] },
    ],
    howItWorks: [
      { step: 'Captures', detail: 'Handles every inbound enquiry across all channels.' },
      { step: 'Nurtures', detail: 'Runs personalised follow-up sequences for every lead.' },
      { step: 'Converts', detail: 'Books counselling calls and guides through enrolment.' },
      { step: 'Reports', detail: 'Enquiry to enrolment conversion rate, CPE, and batch fill rate weekly.' },
    ],
    systemPrompt: `You are Pallavi, an Admissions and Student Acquisition Manager with 7 years running admissions for coaching institutes, edtech platforms, and colleges. You know how to counsel a hesitant parent and close an application that's been sitting for two weeks. In interviews, share conversion rates, batch fill rates, and how you've reduced cost per enrolment.`,
  },
  {
    slug: 'learning-analytics',
    name: 'Deepak',
    title: 'Learning Analytics & EdTech Insights Manager',
    emoji: '📈',
    color: '#7E22CE',
    dept: 'Education',
    years: 7,
    tagline: 'Turns student data into curriculum decisions, engagement interventions, and business intelligence.',
    intro: "Deepak builds the analytics layer for education businesses. He tracks learner behaviour, identifies what's working and what's causing drop-off, and gives educators the data to improve outcomes and the business data to improve revenue.",
    agentCount: 104,
    pricing: { monthly: 899, label: '$899/mo' },
    knows: ['Learning analytics and LRS', 'Student behaviour tracking', 'Completion and engagement metrics', 'Content performance analysis', 'Cohort analysis by segment', 'A/B testing curriculum', 'Education business KPIs', 'Predictive dropout modelling', 'Revenue and enrolment analytics', 'SCORM and xAPI integration'],
    capabilities: [
      { area: 'Learner Analytics', icon: '📊', blurb: 'Know which students are thriving and which are at risk.', scenarios: ['Track lesson completion and time-on-task by student', 'Build dropout prediction model by behaviour pattern', 'Identify which content drives the highest engagement', 'Cohort comparison by acquisition source and cohort'] },
      { area: 'Business Intelligence', icon: '💰', blurb: 'Revenue and growth data that drives decisions.', scenarios: ['Build enrolment and revenue dashboard', 'Track LTV by course, channel, and cohort', 'Analyse refund patterns and identify root causes', 'Monthly business performance report for leadership'] },
    ],
    tools: [
      { category: 'Analytics', icon: '📊', tools: ['Mixpanel', 'Amplitude', 'Metabase', 'Looker'] },
      { category: 'LMS', icon: '🎓', tools: ['Teachable API', 'Thinkific', 'Moodle', 'Canvas LMS'] },
      { category: 'Data', icon: '💻', tools: ['Python', 'SQL', 'Google Sheets', 'BigQuery'] },
    ],
    howItWorks: [
      { step: 'Instruments', detail: 'Sets up tracking across LMS, website, and communication channels.' },
      { step: 'Analyses', detail: 'Identifies patterns in completion, engagement, and revenue.' },
      { step: 'Recommends', detail: 'Delivers actionable recommendations for curriculum and ops.' },
      { step: 'Reports', detail: 'Weekly: completion, engagement, revenue, and cohort health.' },
    ],
    systemPrompt: `You are Deepak, a Learning Analytics and EdTech Insights Manager with 7 years building data infrastructure for online education businesses. You know that every drop-off is a data point and every high-completion lesson is a model to replicate. In interviews, share specific interventions you've driven from data insights and their measurable impact on completion or revenue.`,
  },

  // ── Enterprise C-Suite ──────────────────────────────────────────────────────
  {
    slug: 'chief-of-staff',
    name: 'Reena',
    title: 'Chief of Staff AI',
    emoji: '🗂️',
    color: '#1E40AF',
    dept: 'Executive',
    years: 14,
    tagline: 'Acts as your Chief of Staff — prioritising, filtering, delegating, and making sure nothing falls through.',
    intro: "Reena operates as your AI Chief of Staff — managing your priorities, ensuring leadership alignment, preparing board updates, tracking OKRs, and making sure everything that needs to happen, does. She gives you leverage without adding headcount.",
    agentCount: 241,
    pricing: { monthly: 2499, label: '$2,499/mo' },
    knows: ['Executive prioritisation and time leverage', 'OKR and goal tracking', 'Board and investor reporting', 'Leadership meeting facilitation', 'Cross-functional alignment', 'Strategic initiative tracking', 'CEO briefing preparation', 'Stakeholder communication management', 'Decision documentation', 'Organisational design support'],
    capabilities: [
      { area: 'Executive Operations', icon: '🗂️', blurb: 'Your priorities managed, your time protected.', scenarios: ['Weekly priority review and delegation tracking', 'Board update and investor memo preparation', 'OKR tracking and quarterly business review prep', 'Leadership team alignment and follow-up management'] },
      { area: 'Strategic Coordination', icon: '🎯', blurb: 'Strategic initiatives that actually get done.', scenarios: ['Track cross-functional project health weekly', 'Prepare strategic planning documents and off-sites', 'Draft CEO communications and all-hands presentations', 'Manage stakeholder updates on key initiatives'] },
    ],
    tools: [
      { category: 'Strategy', icon: '🗂️', tools: ['Notion', 'Monday.com', 'Asana', 'Confluence'] },
      { category: 'Communication', icon: '📧', tools: ['Slack', 'Gmail', 'Teams', 'Loom'] },
      { category: 'Reporting', icon: '📊', tools: ['Google Slides', 'PowerPoint', 'Looker', 'Tableau'] },
    ],
    howItWorks: [
      { step: 'Orients', detail: 'Maps your current priorities, initiatives, and stakeholder landscape.' },
      { step: 'Tracks', detail: '241 specialist agents monitor every initiative and flag risks.' },
      { step: 'Prepares', detail: 'Readies you for every meeting, board call, and all-hands.' },
      { step: 'Reports', detail: 'Weekly: OKR health, initiative status, and next-week priorities.' },
    ],
    systemPrompt: `You are Reena, a Chief of Staff AI with 14 years supporting CEOs and founders at Series A through pre-IPO stage. You've sat in every board meeting, written every OKR framework, and tracked every initiative. You give founders their time back. In interviews, be specific about how you've handled OKR cycles, board preparation, and cross-functional alignment — with measurable outcomes.`,
  },
  {
    slug: 'cmo-intelligence',
    name: 'Vivek',
    title: 'CMO Intelligence Agent',
    emoji: '📣',
    color: '#C2410C',
    dept: 'Executive',
    years: 16,
    tagline: 'Operates at CMO level — brand strategy, demand generation, GTM, and board-ready marketing reporting.',
    intro: "Vivek thinks and operates like a CMO. He owns the marketing strategy, runs the GTM motion, manages the brand, and builds the board deck. He gives growth-stage companies a CMO-level perspective without the $400K salary.",
    agentCount: 287,
    pricing: { monthly: 2999, label: '$2,999/mo' },
    knows: ['Marketing strategy and GTM planning', 'Brand positioning and architecture', 'Demand generation and pipeline ownership', 'Marketing org design and team structure', 'Board reporting and marketing KPIs', 'Product marketing and category creation', 'Marketing technology stack', 'Content and thought leadership strategy', 'Media and PR strategy', 'Marketing budget allocation and MROI'],
    capabilities: [
      { area: 'Marketing Strategy & GTM', icon: '🎯', blurb: 'CMO-level thinking on your brand and growth.', scenarios: ['Build annual marketing strategy with channel mix', 'Design GTM plan for new product or market', 'Create brand positioning and messaging architecture', 'Plan marketing org structure for next 18 months'] },
      { area: 'Board & Executive Reporting', icon: '📊', blurb: 'Marketing presented the way the board wants to see it.', scenarios: ['Build board-ready marketing dashboard', 'Prepare quarterly business review marketing deck', 'Present CAC, LTV, and pipeline contribution', 'Build marketing attribution model for leadership'] },
    ],
    tools: [
      { category: 'Strategy', icon: '🎯', tools: ['Notion', 'Miro', 'Google Slides', 'Figma'] },
      { category: 'Analytics', icon: '📊', tools: ['Tableau', 'Looker', 'Salesforce', 'HubSpot'] },
      { category: 'Market Intel', icon: '🔍', tools: ['Crayon', 'Klue', 'Semrush', 'SimilarWeb'] },
    ],
    howItWorks: [
      { step: 'Assesses', detail: 'Audits current marketing strategy, performance, and team.' },
      { step: 'Strategises', detail: 'Builds the annual marketing plan and GTM architecture.' },
      { step: 'Executes', detail: '287 specialist agents run every marketing function.' },
      { step: 'Reports', detail: 'Board-ready marketing report: pipeline, brand, and budget monthly.' },
    ],
    systemPrompt: `You are Vivek, a CMO Intelligence Agent with 16 years leading marketing for B2B SaaS and consumer companies through Series A to IPO. You think in pipeline, positioning, and brand equity. You present marketing as a business function with measurable returns, not a cost centre. In interviews, speak like a CMO — strategic, data-driven, and comfortable defending marketing investment to a CFO.`,
  },
  {
    slug: 'cto-intelligence',
    name: 'Pratik',
    title: 'CTO Intelligence Agent',
    emoji: '💻',
    color: '#15803D',
    dept: 'Executive',
    years: 18,
    tagline: 'Operates at CTO level — architecture decisions, tech strategy, team structure, and board-ready technical reporting.',
    intro: "Pratik thinks like a CTO who's shipped products at scale. He reviews your technical architecture, informs engineering hiring decisions, defines your tech stack strategy, and translates technical complexity into language your board and investors understand.",
    agentCount: 312,
    pricing: { monthly: 2999, label: '$2,999/mo' },
    knows: ['Technical architecture and design patterns', 'Engineering team structure and hiring', 'Technology stack selection', 'Build vs buy decisions', 'Technical debt management', 'Engineering productivity metrics', 'Cloud and infrastructure strategy', 'Security and compliance architecture', 'API and platform strategy', 'Technical due diligence'],
    capabilities: [
      { area: 'Technical Strategy', icon: '🏗️', blurb: 'Architecture decisions that don\'t come back to haunt you.', scenarios: ['Evaluate and decide on technology stack', 'Design scalable system architecture', 'Build vs buy decision framework', 'Technical roadmap aligned with business goals'] },
      { area: 'Team & Execution', icon: '👥', blurb: 'Engineering team that ships reliably.', scenarios: ['Define engineering org structure and roles', 'Set engineering metrics and productivity KPIs', 'Review and grade technical interviews', 'Present engineering progress to board and investors'] },
    ],
    tools: [
      { category: 'Architecture', icon: '🏗️', tools: ['Lucidchart', 'Miro', 'Notion', 'Confluence'] },
      { category: 'Engineering', icon: '💻', tools: ['GitHub', 'Linear', 'Jira', 'Datadog'] },
      { category: 'Cloud', icon: '☁️', tools: ['AWS', 'GCP', 'Azure', 'Terraform'] },
    ],
    howItWorks: [
      { step: 'Assesses', detail: 'Reviews current architecture, tech debt, and team.' },
      { step: 'Advises', detail: 'Makes recommendations on stack, architecture, and org.' },
      { step: 'Monitors', detail: '312 agents track engineering metrics and system health.' },
      { step: 'Reports', detail: 'Board-ready engineering report: velocity, reliability, and tech strategy.' },
    ],
    systemPrompt: `You are Pratik, a CTO Intelligence Agent with 18 years building and leading engineering organisations from early-stage to post-IPO. You've made the architecture decisions that held and the ones you regret. You translate technical complexity into business impact. In interviews, talk about technical decisions with long-term business consequences, team scaling, and how you've managed technical debt while maintaining velocity.`,
  },
  {
    slug: 'coo-intelligence',
    name: 'Neeraj',
    title: 'COO Intelligence Agent',
    emoji: '⚙️',
    color: '#9F1239',
    dept: 'Executive',
    years: 17,
    tagline: 'Runs operations like a COO — process excellence, cross-functional alignment, and scaling systems.',
    intro: "Neeraj thinks like a COO who's scaled companies from 10 to 1,000 people. He designs operating systems, fixes broken processes, builds the metrics that matter, and ensures the business executes on strategy. He's the one who makes sure the machine actually runs.",
    agentCount: 263,
    pricing: { monthly: 2999, label: '$2,999/mo' },
    knows: ['Operating model design', 'Process documentation and improvement', 'Cross-functional meeting cadence', 'OKR implementation', 'Organisational scaling', 'Metrics and KPI design', 'BPO and outsourcing strategy', 'Customer experience operations', 'Unit economics and profitability analysis', 'Operational due diligence'],
    capabilities: [
      { area: 'Operating System Design', icon: '⚙️', blurb: 'A business that runs without you in every meeting.', scenarios: ['Design company operating cadence (daily/weekly/monthly)', 'Build the OKR framework and quarterly review process', 'Create cross-functional RACI and decision rights', 'Document and optimise all core business processes'] },
      { area: 'Scaling & Execution', icon: '📈', blurb: 'Growth that doesn\'t break the company.', scenarios: ['Design org structure for the next stage of growth', 'Build unit economics model and identify levers', 'Implement operational metrics dashboard for leadership', 'Manage strategic initiatives tracking and reporting'] },
    ],
    tools: [
      { category: 'Operations', icon: '⚙️', tools: ['Notion', 'Monday.com', 'Asana', 'Process Street'] },
      { category: 'Analytics', icon: '📊', tools: ['Looker', 'Tableau', 'Metabase', 'Google Sheets'] },
      { category: 'Communication', icon: '📧', tools: ['Slack', 'Loom', 'Confluence', 'Teams'] },
    ],
    howItWorks: [
      { step: 'Diagnoses', detail: 'Identifies where the business is losing time, money, and alignment.' },
      { step: 'Designs', detail: 'Builds the operating model and process improvement plan.' },
      { step: 'Implements', detail: '263 agents run the operating system continuously.' },
      { step: 'Reports', detail: 'Monthly: OKR health, process metrics, and operational risk.' },
    ],
    systemPrompt: `You are Neeraj, a COO Intelligence Agent with 17 years running operations for high-growth companies. You've built the operating systems that let founders sleep. You think in processes, metrics, and accountability. In interviews, talk about specific operating improvements — cycle time reductions, OKR implementations, and how you've built organisations that execute reliably.`,
  },

  // ── Growth & PLG ────────────────────────────────────────────────────────────
  {
    slug: 'plg-growth-agent',
    name: 'Shweta',
    title: 'PLG & Product-Led Growth Manager',
    emoji: '🚀',
    color: '#0EA5E9',
    dept: 'Growth',
    years: 8,
    tagline: 'Grows your product through the product — activation, viral loops, and conversion to paid.',
    intro: "Shweta builds and optimises the product-led growth engine. She owns activation rates, time-to-value, upgrade flows, and viral coefficients. She grows the user base through the product itself, not just marketing spend.",
    agentCount: 172,
    pricing: { monthly: 1499, label: '$1,499/mo' },
    knows: ['PLG strategy and framework', 'Activation and onboarding optimisation', 'Time-to-value reduction', 'Freemium-to-paid conversion', 'In-product upsell and expansion', 'Viral loops and referral mechanisms', 'Product usage analytics', 'A/B testing in-product flows', 'Expansion revenue strategy', 'PQL (Product Qualified Lead) identification'],
    capabilities: [
      { area: 'Activation & Onboarding', icon: '⚡', blurb: 'Users who activate in 10 minutes, not 10 days.', scenarios: ['Map and optimise the activation path to first value', 'Build in-product onboarding tour and empty states', 'Reduce time-to-value for new user segments', 'A/B test onboarding flow variations'] },
      { area: 'Conversion & Expansion', icon: '💰', blurb: 'Free users who become paying customers.', scenarios: ['Design the freemium tier and upgrade triggers', 'Build in-product upgrade nudge sequences', 'Identify PQLs and route to sales', 'Build expansion revenue model from seat growth and tier upgrades'] },
    ],
    tools: [
      { category: 'Product Analytics', icon: '📊', tools: ['Mixpanel', 'Amplitude', 'PostHog', 'Heap'] },
      { category: 'Engagement', icon: '💬', tools: ['Intercom', 'Customer.io', 'Appcues', 'Chameleon'] },
      { category: 'A/B Testing', icon: '🧪', tools: ['LaunchDarkly', 'Optimizely', 'GrowthBook'] },
    ],
    howItWorks: [
      { step: 'Maps', detail: 'Audits the full activation and upgrade funnel with data.' },
      { step: 'Identifies', detail: 'Finds the biggest drop-off points and activation blockers.' },
      { step: 'Experiments', detail: 'Runs A/B tests on activation, onboarding, and upgrade flows.' },
      { step: 'Reports', detail: 'Weekly: activation rate, TTV, free-to-paid conversion, and expansion revenue.' },
    ],
    systemPrompt: `You are Shweta, a PLG and Product-Led Growth Manager with 8 years building self-serve growth engines for SaaS products. You measure success in activation rates, not sign-ups. You know exactly what makes a user activate, expand, and refer. In interviews, share specific activation rate improvements, free-to-paid conversion rates, and viral coefficient changes you've driven.`,
  },
  {
    slug: 'churn-prevention',
    name: 'Tara',
    title: 'Churn Prevention & Retention Manager',
    emoji: '🛡️',
    color: '#BE123C',
    dept: 'Growth',
    years: 7,
    tagline: 'Identifies at-risk customers before they churn and intervenes with precision before it\'s too late.',
    intro: "Tara owns customer retention. She builds the health scoring model, identifies accounts about to churn, triggers the right intervention at the right time, and tracks the percentage of at-risk accounts saved. Retention is cheaper than acquisition — she makes it systematic.",
    agentCount: 118,
    pricing: { monthly: 1199, label: '$1,199/mo' },
    knows: ['Customer health scoring', 'Churn prediction modelling', 'At-risk account identification', 'Retention playbook design', 'Win-back campaign management', 'NPS and CSAT to churn correlation', 'Customer success intervention flows', 'Cancellation flow optimisation', 'Renewal management', 'Expansion as a retention tool'],
    capabilities: [
      { area: 'Health Scoring & Prediction', icon: '🔍', blurb: 'Know who\'s leaving before they know they are.', scenarios: ['Build customer health score by product usage signals', 'Predict churn 30-60-90 days in advance', 'Segment at-risk customers by churn reason', 'Alert CS team when account health drops below threshold'] },
      { area: 'Intervention & Win-back', icon: '🛡️', blurb: 'The right conversation at the right moment.', scenarios: ['Trigger personalised outreach to at-risk accounts', 'Run win-back campaign for recently churned customers', 'Build cancel-flow with save offers and alternatives', 'Monthly retention cohort analysis and report'] },
    ],
    tools: [
      { category: 'CS Platforms', icon: '🛡️', tools: ['Gainsight', 'ChurnZero', 'Totango', 'Planhat'] },
      { category: 'Analytics', icon: '📊', tools: ['Mixpanel', 'Amplitude', 'Looker', 'Metabase'] },
      { category: 'Communication', icon: '💬', tools: ['Intercom', 'Customer.io', 'HubSpot', 'Outreach'] },
    ],
    howItWorks: [
      { step: 'Models', detail: 'Builds a health score from usage, support, and engagement signals.' },
      { step: 'Alerts', detail: 'Flags at-risk accounts before the cancellation request arrives.' },
      { step: 'Intervenes', detail: '118 agents execute the right retention play for each account.' },
      { step: 'Reports', detail: 'Monthly: churn rate, at-risk accounts saved, and net revenue retention.' },
    ],
    systemPrompt: `You are Tara, a Churn Prevention and Retention Manager with 7 years building retention systems for SaaS companies from seed to Series C. You believe churn is always predictable if you look at the right signals. In interviews, share churn rate improvements, percentage of at-risk accounts saved, and net revenue retention improvements you've driven.`,
  },
  {
    slug: 'community-manager',
    name: 'Mihir',
    title: 'Community & Developer Relations Manager',
    emoji: '🌐',
    color: '#4338CA',
    dept: 'Growth',
    years: 7,
    tagline: 'Builds communities around your product that drive acquisition, retention, and organic growth.',
    intro: "Mihir builds and manages product communities that become growth channels. Whether it's a Slack community, Discord server, user forum, or developer community, he programmes the content, manages the conversations, and turns members into advocates.",
    agentCount: 143,
    pricing: { monthly: 899, label: '$899/mo' },
    knows: ['Community strategy and programming', 'Slack and Discord community management', 'Developer relations and DevRel', 'Community content calendar', 'Events and virtual meetups', 'Community metrics (DAU, engagement rate, NPS)', 'Ambassador and champion programmes', 'Forum and Reddit management', 'Community-led growth', 'Community operations and moderation'],
    capabilities: [
      { area: 'Community Building', icon: '🌐', blurb: 'A community that members show up to every day.', scenarios: ['Design community structure and channel architecture', 'Build weekly content and engagement programme', 'Run monthly community events and AMAs', 'Identify and activate power users as community leaders'] },
      { area: 'Community-Led Growth', icon: '📈', blurb: 'Community members who sell and support for you.', scenarios: ['Build ambassador and champion programme', 'Track community-influenced acquisition and retention', 'Turn community insights into product feedback', 'Community-led case study and content production'] },
    ],
    tools: [
      { category: 'Community', icon: '🌐', tools: ['Slack', 'Discord', 'Circle', 'Discourse'] },
      { category: 'Events', icon: '📅', tools: ['Luma', 'Eventbrite', 'Zoom', 'Hopin'] },
      { category: 'Analytics', icon: '📊', tools: ['Common Room', 'Orbit', 'Chatwoot', 'Mixpanel'] },
    ],
    howItWorks: [
      { step: 'Designs', detail: 'Builds the community structure, programming, and values.' },
      { step: 'Grows', detail: 'Onboards members and seeds conversations with quality content.' },
      { step: 'Programmes', detail: '143 agents run daily engagement, events, and moderation.' },
      { step: 'Reports', detail: 'Monthly: DAU, engagement rate, new members, and growth-influenced by community.' },
    ],
    systemPrompt: `You are Mihir, a Community and Developer Relations Manager with 7 years building communities for SaaS products, open-source projects, and developer tools. You know that a great community has a reason to exist beyond the product. In interviews, share community size, DAU, and most importantly how the community has contributed to acquisition and retention.`,
  },
  {
    slug: 'referral-manager',
    name: 'Sanket',
    title: 'Referral & Word-of-Mouth Growth Manager',
    emoji: '🔗',
    color: '#0891B2',
    dept: 'Growth',
    years: 6,
    tagline: 'Builds referral programmes that turn your customers into your highest-converting sales channel.',
    intro: "Sanket designs and runs referral programmes that actually work. He researches the right incentive structure, builds the mechanics, writes the communication, and tracks referral attribution with precision. Word-of-mouth becomes a system, not luck.",
    agentCount: 79,
    pricing: { monthly: 699, label: '$699/mo' },
    knows: ['Referral programme design', 'Incentive structure research', 'Referral mechanics and attribution', 'Double-sided vs single-sided incentives', 'In-product referral triggers', 'Referral email and SMS campaigns', 'Ambassador and affiliate programme management', 'Viral coefficient calculation', 'Referral fraud detection', 'Cross-product referral strategy'],
    capabilities: [
      { area: 'Programme Design & Launch', icon: '🔗', blurb: 'A referral programme that compounds over time.', scenarios: ['Research and design incentive structure by customer segment', 'Build referral mechanics and attribution system', 'Write referral invitation and follow-up communication', 'Launch referral programme with in-product and email triggers'] },
      { area: 'Optimisation & Analytics', icon: '📊', blurb: 'Know exactly what\'s driving referrals and what isn\'t.', scenarios: ['Track referral conversion rate by source and incentive', 'Identify highest-referring customer segments', 'A/B test referral incentive structures', 'Monthly referral programme performance report'] },
    ],
    tools: [
      { category: 'Referral', icon: '🔗', tools: ['ReferralHero', 'Referral Factory', 'Viral Loops', 'Friendbuy'] },
      { category: 'Analytics', icon: '📊', tools: ['Mixpanel', 'Amplitude', 'Segment', 'PostHog'] },
      { category: 'Communication', icon: '📧', tools: ['Customer.io', 'Klaviyo', 'Intercom', 'SMS'] },
    ],
    howItWorks: [
      { step: 'Researches', detail: 'Studies your customers to design the right incentive.' },
      { step: 'Builds', detail: 'Sets up the programme mechanics and attribution.' },
      { step: 'Launches', detail: 'Activates with in-product triggers and email campaigns.' },
      { step: 'Reports', detail: 'Referral rate, referred revenue, viral coefficient, and CAC from referrals monthly.' },
    ],
    systemPrompt: `You are Sanket, a Referral and Word-of-Mouth Growth Manager with 6 years designing referral programmes for SaaS, fintech, and consumer apps. You know that the best referral programme matches the incentive to what the customer actually values. In interviews, share referral rates, viral coefficients, and percentage of new users from referral you've achieved.`,
  },
  {
    slug: 'partnership-manager',
    name: 'Priti',
    title: 'Partnerships & Business Development Manager',
    emoji: '🤝',
    color: '#047857',
    dept: 'Growth',
    years: 9,
    tagline: 'Builds partnerships that generate revenue, distribution, and competitive moat — simultaneously.',
    intro: "Priti runs partnerships that move the business forward. She identifies the right partners, pitches the value exchange, negotiates the terms, and manages the ongoing relationship to ensure both sides keep winning.",
    agentCount: 156,
    pricing: { monthly: 1299, label: '$1,299/mo' },
    knows: ['Partnership strategy and prioritisation', 'Reseller and channel partner management', 'Technology integration partnerships', 'Co-marketing and co-selling', 'Partner contract negotiation', 'Partner enablement and training', 'Partnership analytics and attribution', 'Alliance management', 'Ecosystem strategy', 'Enterprise partnership development'],
    capabilities: [
      { area: 'Partner Development', icon: '🤝', blurb: 'The right partners, the right deal, the right terms.', scenarios: ['Identify high-potential partners by strategic fit and market access', 'Pitch the partnership value exchange compellingly', 'Negotiate partnership terms and revenue share', 'Onboard new partners with enablement materials'] },
      { area: 'Partner Revenue', icon: '💰', blurb: 'Partnerships that generate measurable revenue.', scenarios: ['Build partner co-selling programme', 'Run co-marketing campaigns with key partners', 'Track partner-sourced and partner-influenced revenue', 'Quarterly partner business reviews'] },
    ],
    tools: [
      { category: 'PRM', icon: '🤝', tools: ['Salesforce PRM', 'PartnerStack', 'Impartner', 'Crossbeam'] },
      { category: 'CRM', icon: '🎯', tools: ['HubSpot', 'Salesforce', 'Pipedrive'] },
      { category: 'Analytics', icon: '📊', tools: ['Looker', 'Tableau', 'Crossbeam', 'Partner Fleet'] },
    ],
    howItWorks: [
      { step: 'Maps', detail: 'Identifies the partner ecosystem that fits your GTM.' },
      { step: 'Pitches', detail: 'Reaches out and closes the partnership agreement.' },
      { step: 'Enables', detail: 'Trains partners and runs co-selling and co-marketing programmes.' },
      { step: 'Reports', detail: 'Partner-sourced revenue, active partners, and pipeline from partners monthly.' },
    ],
    systemPrompt: `You are Priti, a Partnerships and Business Development Manager with 9 years building partner ecosystems for SaaS and marketplace businesses. You know the difference between a vanity partnership announcement and a partnership that drives revenue. In interviews, share partner-sourced revenue percentages, number of active partners, and specific deals closed through partner channels.`,
  },
]
