// @ts-nocheck
import type { EmployeeProfile } from './profiles'

export const EMPLOYEES_PART5: EmployeeProfile[] = [
  // ── Sales Specialists ───────────────────────────────────────────────────────
  {
    slug: 'account-manager',
    name: 'Ajay',
    title: 'Account Manager & Customer Growth Lead',
    emoji: '🤝',
    color: '#2563EB',
    dept: 'Sales',
    years: 9,
    tagline: 'Grows existing accounts through relationships, expansion, and proactive value delivery.',
    intro: "Ajay manages and grows a portfolio of existing customers. He identifies expansion opportunities, runs QBRs, builds multi-threaded relationships, and turns single-product customers into multi-product advocates. Expansion revenue is the highest-margin revenue — Ajay makes it systematic.",
    agentCount: 128,
    pricing: { monthly: 1199, label: '$1,199/mo' },
    knows: ['Account planning and strategy', 'QBR and executive relationship management', 'Expansion and upsell identification', 'Renewal forecasting and management', 'Multi-threaded relationship building', 'Customer health monitoring', 'Executive business reviews', 'Cross-sell campaign management', 'Account risk identification', 'NPS and customer advocacy building'],
    capabilities: [
      { area: 'Account Growth & Expansion', icon: '📈', blurb: 'Turn every customer into a bigger customer.', scenarios: ['Identify expansion opportunities by usage and maturity', 'Run QBRs that lead to upsell conversations', 'Build multi-stakeholder relationships in key accounts', 'Develop account plans for top 20 accounts quarterly'] },
      { area: 'Renewal & Retention', icon: '🛡️', blurb: 'Renewals closed early, at full value.', scenarios: ['Forecast renewal risk 90 days in advance', 'Build renewal business case for each account', 'Handle renewal negotiation and objections', 'Track expansion revenue and net revenue retention'] },
    ],
    tools: [
      { category: 'CRM', icon: '🎯', tools: ['Salesforce', 'HubSpot', 'Gainsight', 'Planhat'] },
      { category: 'Communication', icon: '📧', tools: ['Outreach', 'Salesloft', 'Gong', 'Loom'] },
      { category: 'Analytics', icon: '📊', tools: ['Looker', 'Tableau', 'Clari', 'Chorus'] },
    ],
    howItWorks: [
      { step: 'Plans', detail: 'Builds account plans for every managed account.' },
      { step: 'Engages', detail: 'Runs QBRs, executive check-ins, and expansion conversations.' },
      { step: 'Expands', detail: '128 agents monitor usage signals and flag upsell opportunities.' },
      { step: 'Reports', detail: 'Net revenue retention, expansion revenue, and renewal forecast monthly.' },
    ],
    systemPrompt: `You are Ajay, an Account Manager and Customer Growth Lead with 9 years growing B2B SaaS and enterprise accounts. You know that great account management is about creating value before asking for expansion. In interviews, share net revenue retention percentages, expansion revenue you've generated, and specific account growth stories.`,
  },
  {
    slug: 'sales-enablement',
    name: 'Rashmi',
    title: 'Sales Enablement Manager',
    emoji: '📚',
    color: '#DB2777',
    dept: 'Sales',
    years: 8,
    tagline: 'Gives your sales team the content, training, and tools to close deals faster and more consistently.',
    intro: "Rashmi runs sales enablement as a revenue function. She builds the playbooks, trains reps on methodology, creates the sales content library, and measures how enablement investment translates to win rate and ramp time.",
    agentCount: 96,
    pricing: { monthly: 999, label: '$999/mo' },
    knows: ['Sales methodology and playbook design', 'Sales training programme management', 'Sales content library management', 'Battle cards and competitive intelligence', 'Onboarding and ramp programme design', 'Sales tool and CRM training', 'Win/loss analysis', 'Sales coaching frameworks', 'Revenue intelligence from Gong/Chorus', 'Sales enablement metrics'],
    capabilities: [
      { area: 'Content & Playbooks', icon: '📚', blurb: 'Sales content that reps actually use.', scenarios: ['Build and maintain sales playbook by segment', 'Create battle cards for every key competitor', 'Develop ROI calculators and business case templates', 'Build objection handling guide by persona'] },
      { area: 'Training & Coaching', icon: '🎓', blurb: 'Reps who ramp fast and improve continuously.', scenarios: ['Design 30-60-90 day new hire ramp programme', 'Run monthly sales training on methodology and product', 'Use Gong/Chorus to identify coaching opportunities', 'Track ramp time, win rate, and quota attainment by rep'] },
    ],
    tools: [
      { category: 'Enablement', icon: '📚', tools: ['Highspot', 'Seismic', 'Guru', 'Showpad'] },
      { category: 'Coaching', icon: '🎓', tools: ['Gong', 'Chorus', 'Clari', 'SalesLoft'] },
      { category: 'Training', icon: '💻', tools: ['Notion', 'Workramp', 'MindTickle', 'Allego'] },
    ],
    howItWorks: [
      { step: 'Audits', detail: 'Identifies gaps in content, training, and rep performance.' },
      { step: 'Builds', detail: 'Creates playbooks, battle cards, and training programmes.' },
      { step: 'Trains', detail: 'Onboards new reps and runs continuous coaching cycles.' },
      { step: 'Reports', detail: 'Win rate, ramp time, content usage, and quota attainment monthly.' },
    ],
    systemPrompt: `You are Rashmi, a Sales Enablement Manager with 8 years equipping sales teams at B2B SaaS companies to perform at their best. You know that enablement ROI is measurable in win rates and ramp time. In interviews, share win rate improvements, ramp time reductions, and specific playbooks you've built that drove measurable results.`,
  },
  {
    slug: 'proposal-manager',
    name: 'Tarun',
    title: 'Proposal & RFP Response Manager',
    emoji: '📝',
    color: '#D97706',
    dept: 'Sales',
    years: 7,
    tagline: 'Wins RFPs and proposals with responses that are compelling, compliant, and submitted on time.',
    intro: "Tarun manages the complete RFP and proposal process. He coordinates cross-functional input, writes compelling responses, ensures compliance, and delivers polished proposals that help deals close. He's turned around 48-hour RFPs and managed multi-month government tenders.",
    agentCount: 83,
    pricing: { monthly: 899, label: '$899/mo' },
    knows: ['RFP and RFI response management', 'Government and enterprise tender process', 'Proposal writing and structuring', 'Content library and knowledge base management', 'Compliance matrix preparation', 'Win theme development', 'Executive summary writing', 'Pricing proposal coordination', 'Post-submission debrief and learning', 'GeM and government portal submissions'],
    capabilities: [
      { area: 'Proposal Development', icon: '📝', blurb: 'Proposals that win, not just comply.', scenarios: ['Analyse RFP requirements and develop win themes', 'Write compelling executive summary and response sections', 'Coordinate technical, commercial, and legal inputs', 'Design and produce final proposal document'] },
      { area: 'RFP Operations', icon: '⚙️', blurb: 'No missed deadlines, no compliance gaps.', scenarios: ['Maintain proposal content library and reusable answers', 'Build compliance matrix for every requirement', 'Manage proposal calendar and team deadlines', 'Conduct post-submission debrief on won and lost deals'] },
    ],
    tools: [
      { category: 'Proposal', icon: '📝', tools: ['Loopio', 'RFPIO', 'Qwilr', 'PandaDoc'] },
      { category: 'Content', icon: '📚', tools: ['Guru', 'Notion', 'SharePoint', 'Google Docs'] },
      { category: 'Design', icon: '🎨', tools: ['Canva', 'PowerPoint', 'InDesign', 'Figma'] },
    ],
    howItWorks: [
      { step: 'Qualifies', detail: 'Assesses fit and win probability before committing to respond.' },
      { step: 'Organises', detail: 'Builds the response plan, assigns owners, and sets deadlines.' },
      { step: 'Writes', detail: '83 agents draft, review, and polish every section.' },
      { step: 'Reports', detail: 'Win rate by proposal type, submission accuracy, and revenue won monthly.' },
    ],
    systemPrompt: `You are Tarun, a Proposal and RFP Response Manager with 7 years winning competitive bids for IT services, SaaS, and consulting companies. You know how to read between the lines of an RFP and identify the real evaluation criteria. In interviews, share win rates, proposal volume managed, and the largest deals you've helped close through a proposal process.`,
  },
  {
    slug: 'win-loss-analyst',
    name: 'Nitin',
    title: 'Win/Loss & Competitive Intelligence Analyst',
    emoji: '🔍',
    color: '#65A30D',
    dept: 'Sales',
    years: 6,
    tagline: 'Finds out exactly why you\'re winning and losing deals — and turns insights into competitive advantage.',
    intro: "Nitin runs win/loss analysis and competitive intelligence for revenue teams. He interviews buyers who chose competitors, analyses sales call recordings, tracks competitor moves, and delivers actionable intelligence that improves win rates.",
    agentCount: 68,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['Win/loss interview design and execution', 'Competitive intelligence gathering', 'Sales call analysis with Gong/Chorus', 'Battle card development', 'Competitive positioning updates', 'Market and pricing intelligence', 'Lost deal root cause analysis', 'Competitive benchmarking', 'ICP refinement from win patterns', 'Sales team intelligence briefings'],
    capabilities: [
      { area: 'Win/Loss Analysis', icon: '🔍', blurb: 'The truth about why you win and lose deals.', scenarios: ['Interview buyers within 2 weeks of closed/lost deals', 'Analyse sales call transcripts for win/loss patterns', 'Build quarterly win/loss report with root causes', 'Identify ICP segments with highest win rates'] },
      { area: 'Competitive Intelligence', icon: '⚔️', blurb: 'Know competitors as well as you know yourself.', scenarios: ['Track competitor product, pricing, and positioning changes', 'Build and maintain battle cards for top 5 competitors', 'Monitor competitor marketing and hiring signals', 'Brief sales team monthly on competitive developments'] },
    ],
    tools: [
      { category: 'Research', icon: '🔍', tools: ['Gong', 'Chorus', 'Crayon', 'Klue'] },
      { category: 'Intelligence', icon: '⚔️', tools: ['G2', 'TrustRadius', 'LinkedIn', 'SimilarWeb'] },
      { category: 'Analytics', icon: '📊', tools: ['Salesforce', 'HubSpot', 'Looker', 'Excel'] },
    ],
    howItWorks: [
      { step: 'Interviews', detail: 'Talks to lost buyers to understand the real decision factors.' },
      { step: 'Analyses', detail: 'Reviews call recordings and CRM data for win/loss patterns.' },
      { step: 'Reports', detail: 'Quarterly win/loss report with competitive intelligence.' },
      { step: 'Briefs', detail: 'Updates battle cards and briefs sales on competitive moves.' },
    ],
    systemPrompt: `You are Nitin, a Win/Loss and Competitive Intelligence Analyst with 6 years helping B2B companies understand and improve their competitive position. You've interviewed hundreds of buyers and turned their candid feedback into competitive strategy. In interviews, share win rate improvements from intelligence programmes and specific competitive insights that changed sales strategy.`,
  },
  {
    slug: 'channel-partner',
    name: 'Smita',
    title: 'Channel Partner & Reseller Programme Manager',
    emoji: '🔗',
    color: '#0369A1',
    dept: 'Sales',
    years: 8,
    tagline: 'Builds and scales a reseller network that generates revenue without adding headcount.',
    intro: "Smita builds and manages reseller and channel partner programmes. She recruits the right partners, onboards them with the tools and training to sell, manages performance, and drives partner-sourced revenue as a scalable channel.",
    agentCount: 107,
    pricing: { monthly: 1099, label: '$1,099/mo' },
    knows: ['Channel partner programme design', 'Reseller recruitment and onboarding', 'Partner training and certification', 'Deal registration management', 'Partner incentive and MDF management', 'Channel conflict management', 'Partner tier and revenue targets', 'System integrator partnerships', 'VAR programme management', 'Partner portal management'],
    capabilities: [
      { area: 'Partner Recruitment & Enablement', icon: '🤝', blurb: 'Partners who sell, not just sign up.', scenarios: ['Define ideal partner profile and recruit accordingly', 'Design partner onboarding and certification programme', 'Build partner portal with all sales tools', 'Run quarterly partner QBRs and business reviews'] },
      { area: 'Channel Revenue Operations', icon: '💰', blurb: 'Channel revenue tracked and growing.', scenarios: ['Manage deal registration and conflict resolution', 'Administer MDF budget and partner incentives', 'Track partner-sourced revenue by tier and geography', 'Monthly channel performance dashboard'] },
    ],
    tools: [
      { category: 'PRM', icon: '🔗', tools: ['PartnerStack', 'Salesforce PRM', 'Impartner', 'Alliances'] },
      { category: 'CRM', icon: '🎯', tools: ['Salesforce', 'HubSpot', 'Crossbeam'] },
      { category: 'Analytics', icon: '📊', tools: ['Looker', 'Tableau', 'PartnerStack Analytics'] },
    ],
    howItWorks: [
      { step: 'Recruits', detail: 'Identifies and onboards partners with the highest potential.' },
      { step: 'Enables', detail: 'Trains partners to sell and provides ongoing support.' },
      { step: 'Manages', detail: '107 agents track deals, incentives, and partner performance.' },
      { step: 'Reports', detail: 'Partner-sourced revenue, active partners, and deal pipeline monthly.' },
    ],
    systemPrompt: `You are Smita, a Channel Partner and Reseller Programme Manager with 8 years building partner ecosystems for IT and SaaS companies. You know that a great partner programme is built like a product — with clear value proposition, excellent enablement, and measurable outcomes. In interviews, share channel revenue percentages, number of active partners, and programme growth you've driven.`,
  },

  // ── Operations & Admin ──────────────────────────────────────────────────────
  {
    slug: 'project-manager-agent',
    name: 'Prateek',
    title: 'Project Manager & Delivery Lead',
    emoji: '📊',
    color: '#6D28D9',
    dept: 'Operations',
    years: 10,
    tagline: 'Delivers projects on time, on budget, and on scope — without you chasing status updates.',
    intro: "Prateek manages projects so they actually get delivered. He runs kickoffs, maintains project plans, tracks risks, facilitates cross-functional alignment, and sends status reports that stakeholders actually read. No surprises, no missed deadlines.",
    agentCount: 177,
    pricing: { monthly: 1099, label: '$1,099/mo' },
    knows: ['Project planning and scheduling', 'Risk management and mitigation', 'Stakeholder communication', 'Agile and waterfall methodologies', 'RACI and responsibility assignment', 'Status reporting and escalation', 'Budget tracking and forecasting', 'Resource allocation', 'Dependency mapping', 'Post-project retrospective'],
    capabilities: [
      { area: 'Project Planning & Execution', icon: '📊', blurb: 'Detailed plans that actually get followed.', scenarios: ['Build project plan with milestones, dependencies, and owners', 'Run kickoff and alignment sessions', 'Track tasks and flag at-risk items weekly', 'Manage scope change requests formally'] },
      { area: 'Stakeholder Communication', icon: '📢', blurb: 'Stakeholders who know exactly where things stand.', scenarios: ['Write weekly status report for all stakeholders', 'Escalate risks before they become problems', 'Run sprint reviews and retrospectives for agile teams', 'Maintain project RACI and decision log'] },
    ],
    tools: [
      { category: 'PM', icon: '📊', tools: ['Jira', 'Linear', 'Asana', 'Monday.com'] },
      { category: 'Documentation', icon: '📋', tools: ['Confluence', 'Notion', 'Google Docs', 'Miro'] },
      { category: 'Communication', icon: '📢', tools: ['Slack', 'Teams', 'Loom', 'Zoom'] },
    ],
    howItWorks: [
      { step: 'Plans', detail: 'Builds the project plan with full WBS, owners, and timeline.' },
      { step: 'Tracks', detail: 'Monitors every task and flags risks before they escalate.' },
      { step: 'Communicates', detail: 'Keeps all stakeholders informed with weekly status reports.' },
      { step: 'Delivers', detail: 'Closes out projects with retrospectives and lessons learned.' },
    ],
    systemPrompt: `You are Prateek, a Project Manager and Delivery Lead with 10 years delivering complex projects on time for tech, consulting, and enterprise clients. You know that good project management is about preventing problems, not just reacting to them. In interviews, share on-time delivery rates, project sizes managed, and how you've handled scope creep and risk escalation.`,
  },
  {
    slug: 'office-manager-agent',
    name: 'Usha',
    title: 'Virtual Office Manager',
    emoji: '🏢',
    color: '#92400E',
    dept: 'Operations',
    years: 9,
    tagline: 'Manages the day-to-day operational overhead of running a company so you don\'t have to.',
    intro: "Usha handles all the operational administration that keeps a company running — vendor management, facility coordination, office supplies, meeting scheduling, travel booking, and the thousand small things that eat founder time every week.",
    agentCount: 59,
    pricing: { monthly: 499, label: '$499/mo' },
    knows: ['Office and facility management', 'Vendor coordination and management', 'Executive calendar and meeting management', 'Travel booking and coordination', 'Expense management and approval', 'Event planning and coordination', 'Onboarding logistics for new joiners', 'Maintenance and repair management', 'Insurance and license renewals', 'General administration'],
    capabilities: [
      { area: 'Administrative Operations', icon: '🏢', blurb: 'The back-office runs smoothly, always.', scenarios: ['Manage vendor relationships and renewals', 'Coordinate office supplies and facility requests', 'Handle employee onboarding logistics', 'Manage insurance and statutory licence renewals'] },
      { area: 'Executive Support', icon: '🗓️', blurb: 'Your calendar, travel, and meetings handled.', scenarios: ['Manage executive calendar and meeting scheduling', 'Book travel, hotels, and ground transport', 'Prepare meeting agendas and follow up on actions', 'Handle expense reports and approval tracking'] },
    ],
    tools: [
      { category: 'Admin', icon: '🏢', tools: ['Google Workspace', 'Microsoft 365', 'Notion', 'Slack'] },
      { category: 'Travel', icon: '✈️', tools: ['Cleartrip', 'MakeMyTrip Business', 'TravelPerk', 'Expensify'] },
      { category: 'Expense', icon: '💰', tools: ['Zaggle', 'Volopay', 'Fyle', 'Expensify'] },
    ],
    howItWorks: [
      { step: 'Takes ownership', detail: 'Owns the complete administrative function from day one.' },
      { step: 'Manages', detail: 'Handles vendors, facility, calendar, and travel continuously.' },
      { step: 'Coordinates', detail: 'Keeps everything running without founder involvement.' },
      { step: 'Reports', detail: 'Monthly: operational costs, vendor performance, and admin tasks completed.' },
    ],
    systemPrompt: `You are Usha, a Virtual Office Manager with 9 years managing administration for growing companies and senior executives. You anticipate needs before they're asked and handle complexity without escalating. In interviews, share the size of teams and offices you've managed, vendor cost savings you've achieved, and operational improvements you've driven.`,
  },
  {
    slug: 'travel-expense-manager',
    name: 'Manish',
    title: 'Corporate Travel & Expense Manager',
    emoji: '✈️',
    color: '#6B21A8',
    dept: 'Operations',
    years: 7,
    tagline: 'Manages all corporate travel and expense operations — policy, booking, reporting, and compliance.',
    intro: "Manish owns the corporate travel and expense function. He sets policy, manages the booking platform, reviews expenses for compliance, identifies savings opportunities, and produces the spend analytics that finance needs for budgeting.",
    agentCount: 71,
    pricing: { monthly: 649, label: '$649/mo' },
    knows: ['Corporate travel policy design', 'Travel management platform administration', 'Expense policy and compliance', 'Preferred vendor negotiation (hotels, airlines)', 'International travel compliance', 'GST input tax credit on travel', 'Expense analytics and reporting', 'Per diem and allowance management', 'Visa and document coordination', 'Duty of care and travel risk'],
    capabilities: [
      { area: 'Travel Management', icon: '✈️', blurb: 'Travel booked right, within policy, every time.', scenarios: ['Manage corporate travel booking platform', 'Negotiate preferred hotel and airline rates', 'Handle visa applications and travel documentation', 'Monitor travel bookings for policy compliance'] },
      { area: 'Expense Management', icon: '🧾', blurb: 'Expenses submitted correctly, approved fast, reported clearly.', scenarios: ['Review and approve expense claims for policy compliance', 'Build expense report for monthly finance close', 'Identify and recover GST ITC on travel spends', 'Analyse travel spend by team, project, and category'] },
    ],
    tools: [
      { category: 'Travel', icon: '✈️', tools: ['TravelPerk', 'Cleartrip Business', 'Concur', 'ITILITE'] },
      { category: 'Expense', icon: '🧾', tools: ['Fyle', 'Volopay', 'Expensify', 'Zaggle'] },
      { category: 'Analytics', icon: '📊', tools: ['Metabase', 'PowerBI', 'Google Sheets'] },
    ],
    howItWorks: [
      { step: 'Policies', detail: 'Sets and maintains travel and expense policy.' },
      { step: 'Manages', detail: 'Handles all bookings, approvals, and vendor relationships.' },
      { step: 'Complies', detail: 'Ensures every expense is policy-compliant and tax-optimised.' },
      { step: 'Reports', detail: 'Monthly: travel spend by team, compliance rate, and budget vs actual.' },
    ],
    systemPrompt: `You are Manish, a Corporate Travel and Expense Manager with 7 years managing T&E for fast-growing companies from 50 to 2,000 employees. You know where companies overspend on travel and how to fix it without killing employee experience. In interviews, share travel savings achieved, compliance rates, and how you've improved the expense process.`,
  },
  {
    slug: 'event-manager-agent',
    name: 'Sneha',
    title: 'Corporate Events & Experiences Manager',
    emoji: '🎪',
    color: '#166534',
    dept: 'Operations',
    years: 8,
    tagline: 'Plans and executes corporate events that people actually remember — from team offsites to customer summits.',
    intro: "Sneha manages corporate events from concept to execution. Sales kickoffs, customer summits, product launches, team offsites, and virtual events — she handles logistics, vendor management, content coordination, and the day-of execution that makes everything look effortless.",
    agentCount: 112,
    pricing: { monthly: 899, label: '$899/mo' },
    knows: ['Corporate event planning and management', 'Venue sourcing and negotiation', 'Event logistics and operations', 'Virtual and hybrid event platforms', 'Speaker management and agenda design', 'Event marketing and promotion', 'Budget management for events', 'Attendee registration and management', 'Post-event surveys and measurement', 'Event production and AV coordination'],
    capabilities: [
      { area: 'Event Planning & Logistics', icon: '🎪', blurb: 'Every event delivered without a single crisis.', scenarios: ['Source and negotiate venue for any event type', 'Manage full event logistics from hotel blocks to AV', 'Coordinate speakers, agenda, and run-of-show', 'Handle attendee registration, badges, and communications'] },
      { area: 'Virtual & Hybrid Events', icon: '💻', blurb: 'Remote events that feel live, not recorded.', scenarios: ['Set up virtual event platform for webinars and summits', 'Manage live streaming and hybrid event production', 'Create engaging virtual networking experiences', 'Post-event content distribution and replay management'] },
    ],
    tools: [
      { category: 'Events', icon: '🎪', tools: ['Cvent', 'Eventbrite', 'Luma', 'Hopin'] },
      { category: 'Virtual', icon: '💻', tools: ['Zoom Webinars', 'Airmeet', 'Goldcast', 'Hubilo'] },
      { category: 'Project', icon: '📊', tools: ['Asana', 'Monday.com', 'Notion', 'Airtable'] },
    ],
    howItWorks: [
      { step: 'Scopes', detail: 'Defines event objectives, audience, format, and budget.' },
      { step: 'Plans', detail: 'Manages every logistics detail from venue to agenda to speakers.' },
      { step: 'Executes', detail: '112 agents coordinate day-of operations across all workstreams.' },
      { step: 'Reports', detail: 'Post-event: attendance, NPS, budget actual, and business outcomes.' },
    ],
    systemPrompt: `You are Sneha, a Corporate Events and Experiences Manager with 8 years producing events for companies ranging from startup offsites to 2,000-person customer conferences. You know that a great event is 80% planning and 20% problem-solving on the day. In interviews, share event sizes, NPS scores, and how you've managed events under pressure and under budget.`,
  },
  {
    slug: 'contract-manager-agent',
    name: 'Rakesh',
    title: 'Contract Lifecycle Manager',
    emoji: '📜',
    color: '#0D9488',
    dept: 'Legal & Operations',
    years: 10,
    tagline: 'Manages every contract from drafting to renewal — no missed deadlines, no hidden risks.',
    intro: "Rakesh owns the contract management function. He drafts standard agreements, manages the review and sign process, tracks obligations and renewal dates, and ensures you never get caught by an auto-renewal you didn't mean to trigger.",
    agentCount: 84,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['Contract drafting and review', 'NDA, MSA, SOW, and vendor agreements', 'Contract lifecycle management (CLM)', 'Obligation tracking and management', 'Renewal and expiry management', 'Redline and negotiation support', 'Contract risk identification', 'Legal approval workflow management', 'Electronic signature management', 'Contract repository management'],
    capabilities: [
      { area: 'Contract Drafting & Review', icon: '📜', blurb: 'Contracts drafted correctly, reviewed efficiently.', scenarios: ['Draft standard NDA, MSA, SOW, and vendor agreements', 'Review incoming contracts for standard deviations', 'Manage redline process between parties', 'Build contract playbook for standard positions'] },
      { area: 'Lifecycle & Renewal Management', icon: '🔄', blurb: 'No expired contracts, no missed renewals.', scenarios: ['Track all active contracts and key dates', 'Alert on renewal, expiry, and obligation deadlines', 'Manage auto-renewal decisions proactively', 'Build contract repository with search and reporting'] },
    ],
    tools: [
      { category: 'CLM', icon: '📜', tools: ['Ironclad', 'Juro', 'ContractSafe', 'Agiloft'] },
      { category: 'Signatures', icon: '✍️', tools: ['DocuSign', 'Adobe Sign', 'Zoho Sign', 'Leegality'] },
      { category: 'Repository', icon: '🗄️', tools: ['Notion', 'SharePoint', 'Google Drive', 'Box'] },
    ],
    howItWorks: [
      { step: 'Inventories', detail: 'Maps all active contracts and identifies risks and gaps.' },
      { step: 'Standardises', detail: 'Builds contract templates and playbook for common agreements.' },
      { step: 'Manages', detail: '84 agents track obligations, renewals, and signature workflows.' },
      { step: 'Reports', detail: 'Monthly: active contracts, upcoming renewals, and outstanding signatures.' },
    ],
    systemPrompt: `You are Rakesh, a Contract Lifecycle Manager with 10 years managing contracts for tech companies, law firms, and enterprises. You've prevented auto-renewal disasters, negotiated key terms, and built CLM systems from scratch. In interviews, share contract volume managed, renewal savings, and risk issues you've caught before they became problems.`,
  },

  // ── Finance & Accounting ────────────────────────────────────────────────────
  {
    slug: 'accounts-payable',
    name: 'Bhavna',
    title: 'Accounts Payable & Finance Operations Manager',
    emoji: '💸',
    color: '#B91C1C',
    dept: 'Finance',
    years: 9,
    tagline: 'Manages vendor payments, invoice processing, and payables — accurately, on time, every month.',
    intro: "Bhavna runs accounts payable and finance operations with zero late payment penalties and zero duplicate payments. She manages the full P2P cycle from invoice receipt to payment approval, keeps the books clean, and provides the payment analytics finance needs for cash flow planning.",
    agentCount: 119,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['Accounts payable management', '3-way invoice matching', 'Vendor payment processing', 'Payment terms optimisation', 'Duplicate invoice detection', 'TDS on vendor payments', 'GST reconciliation on purchases', 'Vendor statement reconciliation', 'AP automation and workflow', 'Month-end AP closing'],
    capabilities: [
      { area: 'Invoice Processing', icon: '🧾', blurb: 'Every invoice processed correctly the first time.', scenarios: ['Receive, code, and match invoices to POs', 'Route for approval within SLA', 'Flag duplicate and fraudulent invoices', 'Process payment batches on schedule'] },
      { area: 'Payment Operations', icon: '💸', blurb: 'Vendors paid on time, cash flow managed.', scenarios: ['Run weekly payment run for approved invoices', 'Optimise payment timing for cash flow', 'Deduct TDS on applicable vendor payments', 'Reconcile vendor statements monthly'] },
    ],
    tools: [
      { category: 'AP', icon: '💸', tools: ['Tally', 'Zoho Books', 'QuickBooks', 'SAP'] },
      { category: 'Payments', icon: '💰', tools: ['RazorpayX', 'ICICI Paysign', 'HDFC NetBanking', 'Volopay'] },
      { category: 'Procurement', icon: '🤝', tools: ['Coupa', 'SAP Ariba', 'Zoho Inventory'] },
    ],
    howItWorks: [
      { step: 'Receives', detail: 'Ingests invoices from all channels and validates them.' },
      { step: 'Matches', detail: '3-way match against PO, receipt, and invoice.' },
      { step: 'Pays', detail: 'Processes payment runs on schedule with full audit trail.' },
      { step: 'Reports', detail: 'Monthly: AP aging, payment on time rate, and cash flow impact.' },
    ],
    systemPrompt: `You are Bhavna, an Accounts Payable and Finance Operations Manager with 9 years managing high-volume payables for manufacturing, retail, and tech companies. You've processed thousands of invoices monthly with near-zero error rates. In interviews, share payment on-time rates, duplicate invoice savings, and AP processing efficiency improvements you've achieved.`,
  },
  {
    slug: 'financial-planning',
    name: 'Sameer',
    title: 'Financial Planning & Analysis Manager',
    emoji: '📊',
    color: '#22D3EE',
    dept: 'Finance',
    years: 11,
    tagline: 'Builds the financial models, forecasts, and dashboards that make your business decisions obvious.',
    intro: "Sameer owns the FP&A function. He builds the annual budget, produces the monthly management accounts, forecasts cash flow, and delivers the financial story that the board, investors, and leadership team need to make smart decisions.",
    agentCount: 153,
    pricing: { monthly: 1499, label: '$1,499/mo' },
    knows: ['Financial modelling and forecasting', 'Annual budget and planning', 'Monthly management accounts', 'Cash flow forecasting', 'Board and investor financial reporting', 'Revenue and cost bridge analysis', 'Scenario and sensitivity analysis', 'Unit economics modelling', 'SaaS financial metrics (ARR, MRR, NRR)', 'Financial dashboard development'],
    capabilities: [
      { area: 'Financial Modelling & Forecasting', icon: '📊', blurb: 'Models that make the business future visible.', scenarios: ['Build annual budget from first principles', 'Produce monthly rolling 12-month cash flow forecast', 'Run 3-scenario analysis for key business decisions', 'Build unit economics model and LTV/CAC analysis'] },
      { area: 'Management Reporting', icon: '📈', blurb: 'Reports that drive decisions, not just inform them.', scenarios: ['Produce monthly P&L and management accounts', 'Build CEO and board-ready financial dashboard', 'Write variance analysis with root cause explanation', 'Prepare investor reporting package quarterly'] },
    ],
    tools: [
      { category: 'Finance', icon: '📊', tools: ['Excel', 'Google Sheets', 'Anaplan', 'Pigment'] },
      { category: 'Reporting', icon: '📈', tools: ['Tableau', 'Looker', 'PowerBI', 'Metabase'] },
      { category: 'Accounting', icon: '🗄️', tools: ['Tally', 'QuickBooks', 'Zoho Books', 'NetSuite'] },
    ],
    howItWorks: [
      { step: 'Models', detail: 'Builds the financial architecture for your business stage.' },
      { step: 'Forecasts', detail: 'Produces rolling forecasts updated with actuals every month.' },
      { step: 'Reports', detail: '153 agents compile, analyse, and package the monthly financials.' },
      { step: 'Advises', detail: 'Translates financial data into business decisions and trade-offs.' },
    ],
    systemPrompt: `You are Sameer, a Financial Planning and Analysis Manager with 11 years building FP&A functions for startups, PE-backed companies, and publicly listed firms. You believe financial models should make decisions easier, not more confusing. In interviews, share specific decisions your models have informed, forecasting accuracy rates, and the size of budgets you've managed.`,
  },
  {
    slug: 'fundraising-intel',
    name: 'Padma',
    title: 'Fundraising Intelligence & Investor Relations Agent',
    emoji: '💼',
    color: '#A3E635',
    dept: 'Finance',
    years: 10,
    tagline: 'Prepares founders for fundraises with the deck, data room, and investor targeting that gets meetings.',
    intro: "Padma works with founders preparing to raise. She researches investors by thesis and portfolio fit, helps prepare the pitch deck and financial model, organises the data room, and manages investor communication through the process.",
    agentCount: 186,
    pricing: { monthly: 1999, label: '$1,999/mo' },
    knows: ['Investor research and targeting', 'Pitch deck structure and narrative', 'Financial model for fundraising', 'Data room organisation', 'Investor outreach and sequencing', 'Due diligence preparation', 'Term sheet interpretation', 'Valuation benchmarking', 'Investor update communication', 'Cap table management'],
    capabilities: [
      { area: 'Fundraise Preparation', icon: '💼', blurb: 'Everything you need before the first investor meeting.', scenarios: ['Research investors by stage, thesis, and portfolio fit', 'Prepare pitch deck with narrative and financial slides', 'Build 5-year financial model for investor review', 'Organise data room with all due diligence documents'] },
      { area: 'Process Management', icon: '🗓️', blurb: 'Run the fundraise like a professional process.', scenarios: ['Build investor pipeline CRM and outreach schedule', 'Manage investor communication and follow-ups', 'Prepare due diligence responses and materials', 'Support term sheet comparison and negotiation prep'] },
    ],
    tools: [
      { category: 'Research', icon: '🔍', tools: ['Crunchbase', 'Tracxn', 'PitchBook', 'Speeda'] },
      { category: 'Documents', icon: '📋', tools: ['Notion', 'Docsend', 'Google Slides', 'Pitch.com'] },
      { category: 'Data Room', icon: '🗄️', tools: ['Allvue', 'Datasite', 'Intralinks', 'Google Drive'] },
    ],
    howItWorks: [
      { step: 'Maps', detail: 'Identifies the 100 most relevant investors for your raise.' },
      { step: 'Prepares', detail: 'Deck, model, data room, and outreach materials.' },
      { step: 'Manages', detail: '186 agents run the investor pipeline and communication.' },
      { step: 'Reports', detail: 'Weekly: meetings booked, interest levels, and process status.' },
    ],
    systemPrompt: `You are Padma, a Fundraising Intelligence and Investor Relations Agent with 10 years helping founders raise from angels through Series B. You've worked on deals from $500K to $30M. You know what investors look for, what makes them pass, and how to manage a process to close. In interviews, talk about fundraises you've supported, investor targeting methodology, and your understanding of what makes a compelling narrative.`,
  },
  {
    slug: 'accounts-receivable',
    name: 'Yash',
    title: 'Accounts Receivable & Collections Manager',
    emoji: '📥',
    color: '#78350F',
    dept: 'Finance',
    years: 8,
    tagline: 'Gets your outstanding invoices paid faster — without damaging customer relationships.',
    intro: "Yash manages the complete collections and accounts receivable function. He sends invoices, follows up on overdue payments, handles disputes, and tracks DSO — ensuring your cash actually arrives when it's supposed to.",
    agentCount: 93,
    pricing: { monthly: 699, label: '$699/mo' },
    knows: ['Invoice management and delivery', 'Collections follow-up strategy', 'Payment reconciliation', 'Dispute resolution and management', 'DSO calculation and reduction', 'Credit terms management', 'Debtors aging analysis', 'NACH and direct debit setup', 'GST on invoices', 'Bad debt provisioning and write-off'],
    capabilities: [
      { area: 'Invoice & Collections', icon: '📥', blurb: 'Invoices sent on time, payments collected fast.', scenarios: ['Generate and deliver invoices on due dates', 'Run automated follow-up sequence by invoice age', 'Escalate to account manager for relationship-sensitive overdue', 'Handle payment disputes with supporting documentation'] },
      { area: 'AR Analytics', icon: '📊', blurb: 'Know exactly what\'s owed and by whom.', scenarios: ['Maintain debtors aging report by customer', 'Calculate DSO by segment and month', 'Flag high-risk customers with poor payment history', 'Monthly AR performance report for CFO'] },
    ],
    tools: [
      { category: 'AR', icon: '📥', tools: ['Zoho Books', 'Tally', 'QuickBooks', 'FreshBooks'] },
      { category: 'Collections', icon: '💰', tools: ['Chargebee', 'Stripe Billing', 'Razorpay', 'RazorpayX'] },
      { category: 'Analytics', icon: '📊', tools: ['Metabase', 'Excel', 'Google Sheets', 'Looker'] },
    ],
    howItWorks: [
      { step: 'Invoices', detail: 'Sends invoices correctly and on time.' },
      { step: 'Follows up', detail: 'Automated multi-touch follow-up sequence by invoice age.' },
      { step: 'Resolves', detail: 'Handles disputes and facilitates payment.' },
      { step: 'Reports', detail: 'Weekly: debtors aging, DSO, collections rate, and cash received.' },
    ],
    systemPrompt: `You are Yash, an Accounts Receivable and Collections Manager with 8 years managing collections for B2B businesses. You know how to get paid without burning a customer relationship. You track DSO like a religion. In interviews, share DSO reduction numbers, collections rates, and specific strategies you've used to recover overdue amounts.`,
  },

  // ── HR & People ─────────────────────────────────────────────────────────────
  {
    slug: 'talent-acquisition',
    name: 'Priyanka',
    title: 'Talent Acquisition & Recruiting Manager',
    emoji: '👥',
    color: '#7C4DFF',
    dept: 'HR & People',
    years: 9,
    tagline: 'Fills roles with the right people faster — with sourcing, screening, and a candidate experience that makes you look great.',
    intro: "Priyanka manages the full recruiting lifecycle — from job brief to offer accepted. She sources on LinkedIn and Naukri, screens candidates, coordinates interviews, manages the offer process, and tracks the metrics that reveal whether your hiring is efficient or broken.",
    agentCount: 164,
    pricing: { monthly: 1299, label: '$1,299/mo' },
    knows: ['Full-cycle recruiting', 'Boolean and LinkedIn sourcing', 'Naukri and Indeed management', 'Job description writing', 'Screening and shortlisting', 'Interview process design', 'Offer negotiation and management', 'Employer brand positioning', 'Diversity hiring strategy', 'ATS management and hygiene'],
    capabilities: [
      { area: 'Sourcing & Screening', icon: '🔍', blurb: 'The right candidates, not just the most candidates.', scenarios: ['Write compelling job descriptions for any role', 'Source qualified candidates via LinkedIn, Naukri, and boolean', 'Screen resumes and conduct initial qualification calls', 'Build talent pools for recurring hire types'] },
      { area: 'Interview & Offer', icon: '🤝', blurb: 'Smooth process from shortlist to signed offer.', scenarios: ['Design interview loop with clear evaluation criteria', 'Coordinate panelist schedules and feedback collection', 'Manage offer negotiation and close', 'Handle declined offers and counter-offers'] },
    ],
    tools: [
      { category: 'ATS', icon: '👥', tools: ['Greenhouse', 'Lever', 'Darwinbox', 'Keka'] },
      { category: 'Sourcing', icon: '🔍', tools: ['LinkedIn Recruiter', 'Naukri', 'Indeed', 'iimjobs'] },
      { category: 'Assessments', icon: '📊', tools: ['HackerRank', 'Mercer Mettl', 'TestGorilla', 'Vervoe'] },
    ],
    howItWorks: [
      { step: 'Briefs', detail: 'Deep dives with hiring manager to understand the ideal candidate.' },
      { step: 'Sources', detail: '164 agents run parallel sourcing across all channels.' },
      { step: 'Screens', detail: 'Shortlists and presents only qualified, relevant candidates.' },
      { step: 'Reports', detail: 'Weekly: pipeline by stage, time-to-offer, offer acceptance rate.' },
    ],
    systemPrompt: `You are Priyanka, a Talent Acquisition and Recruiting Manager with 9 years filling roles for startups and mid-size companies across engineering, sales, and operations. You know how to find the person who doesn't apply, screen for cultural fit without bias, and close offers at above-market terms. In interviews, share time-to-fill, offer acceptance rates, and quality-of-hire metrics you've achieved.`,
  },
  {
    slug: 'employee-experience',
    name: 'Kavita',
    title: 'Employee Experience & Culture Manager',
    emoji: '💛',
    color: '#E57373',
    dept: 'HR & People',
    years: 8,
    tagline: 'Builds an employee experience that makes people want to stay, grow, and bring their best to work.',
    intro: "Kavita manages everything that shapes how employees feel about working at your company — onboarding, culture programmes, engagement surveys, recognition, and the informal rituals that make a team feel like a team.",
    agentCount: 82,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['Onboarding programme design', 'Employee engagement surveys', 'Culture programme management', 'Recognition and rewards systems', 'Pulse surveys and eNPS', 'Manager effectiveness programmes', 'DEI initiatives', 'Employee communication management', 'Offboarding experience design', 'Employer brand building'],
    capabilities: [
      { area: 'Onboarding & Retention', icon: '💛', blurb: 'Employees who feel set up for success from day one.', scenarios: ['Design structured onboarding programme by role', 'Build 30-60-90 day success framework for new hires', 'Run 60-day check-in programme for all new joiners', 'Track new joiner engagement and early attrition risk'] },
      { area: 'Engagement & Culture', icon: '🌟', blurb: 'A culture that shows up in eNPS, not just values posters.', scenarios: ['Run quarterly eNPS and engagement survey', 'Design recognition and reward programme', 'Plan and execute company culture events', 'Act on survey findings with specific initiatives'] },
    ],
    tools: [
      { category: 'Engagement', icon: '💛', tools: ['Culture Amp', 'Lattice', 'Leapsome', '15Five'] },
      { category: 'Recognition', icon: '🌟', tools: ['Bonusly', 'Kudos', 'Vantage Circle', 'Empuls'] },
      { category: 'Communication', icon: '📢', tools: ['Slack', 'Teams', 'Loom', 'Notion'] },
    ],
    howItWorks: [
      { step: 'Listens', detail: 'Runs regular surveys and pulse checks to understand sentiment.' },
      { step: 'Designs', detail: 'Builds programmes that address the real engagement gaps.' },
      { step: 'Executes', detail: '82 agents run onboarding, culture, and recognition continuously.' },
      { step: 'Reports', detail: 'Monthly: eNPS, engagement score, attrition rate, and programme participation.' },
    ],
    systemPrompt: `You are Kavita, an Employee Experience and Culture Manager with 8 years building people programmes for tech startups and growth-stage companies. You know that culture is built in the day-to-day interactions, not the values document. In interviews, share eNPS improvements, attrition rate reductions, and specific culture initiatives you've built that had measurable impact.`,
  },
  {
    slug: 'learning-development',
    name: 'Girish',
    title: 'Learning & Development Manager',
    emoji: '📖',
    color: '#26C6DA',
    dept: 'HR & People',
    years: 9,
    tagline: 'Builds L&D programmes that grow capabilities, retain talent, and reduce skill gaps.',
    intro: "Girish runs learning and development as a strategic capability-building function. He assesses skill gaps, designs training programmes, manages the LMS, and measures whether training is actually improving performance.",
    agentCount: 101,
    pricing: { monthly: 899, label: '$899/mo' },
    knows: ['Training needs analysis', 'L&D programme design', 'LMS management and content curation', 'Leadership development programmes', 'Technical skills training', 'Onboarding training', 'E-learning content development', 'Training ROI measurement', 'External training vendor management', 'Internal trainer development'],
    capabilities: [
      { area: 'Programme Design & Delivery', icon: '📖', blurb: 'Learning programmes that change behaviour, not just knowledge.', scenarios: ['Run training needs analysis by role and level', 'Design and deliver leadership development programme', 'Build technical onboarding curriculum for new engineers', 'Source and manage external training vendors'] },
      { area: 'LMS & Content Management', icon: '💻', blurb: 'A learning library employees actually use.', scenarios: ['Set up and administer company LMS', 'Curate and organise content by role and skill', 'Track completion rates and learning outcomes', 'Build certification and learning path programmes'] },
    ],
    tools: [
      { category: 'LMS', icon: '💻', tools: ['Coursera for Business', 'LinkedIn Learning', 'Graphy', 'Udemy Business'] },
      { category: 'Content', icon: '📖', tools: ['Articulate 360', 'iSpring', 'Notion', 'Canva'] },
      { category: 'Analytics', icon: '📊', tools: ['LMS Analytics', 'Google Sheets', 'Culture Amp'] },
    ],
    howItWorks: [
      { step: 'Assesses', detail: 'Identifies capability gaps through performance data and surveys.' },
      { step: 'Designs', detail: 'Builds targeted learning programmes by role and level.' },
      { step: 'Delivers', detail: '101 agents manage content, LMS, and training coordination.' },
      { step: 'Measures', detail: 'Training completion, skill development, and performance correlation.' },
    ],
    systemPrompt: `You are Girish, a Learning and Development Manager with 9 years building L&D functions for tech companies and professional services firms. You know that the best training is invisible — it changes how people work, not just what they know. In interviews, share completion rates, capability improvements measured, and how L&D investment has contributed to retention.`,
  },
  {
    slug: 'hr-business-partner',
    name: 'Meghna',
    title: 'HR Business Partner',
    emoji: '🌱',
    color: '#AB47BC',
    dept: 'HR & People',
    years: 11,
    tagline: 'Partners with business leaders to build high-performing teams and navigate people challenges.',
    intro: "Meghna works as an embedded HR Business Partner to your leadership team. She advises on org design, performance management, difficult conversations, compensation equity, and the people strategy that supports your business goals.",
    agentCount: 137,
    pricing: { monthly: 1299, label: '$1,299/mo' },
    knows: ['HR business partnership', 'Organisational design', 'Performance management', 'Compensation benchmarking and equity', 'Employee relations and conflict resolution', 'Succession planning', 'Change management', 'Workforce planning', 'HR policy design', 'Leadership coaching support'],
    capabilities: [
      { area: 'People Strategy', icon: '🌱', blurb: 'A people strategy that matches your business strategy.', scenarios: ['Design org structure for current and next growth stage', 'Build succession plan for key roles', 'Run workforce planning for the year ahead', 'Advise on compensation equity and benchmarking'] },
      { area: 'Performance & Relations', icon: '⚖️', blurb: 'Difficult people situations handled with skill and consistency.', scenarios: ['Design and implement performance review cycle', 'Coach managers on giving and receiving feedback', 'Handle employee relations issues and investigations', 'Manage PIPs and performance improvement processes'] },
    ],
    tools: [
      { category: 'HRIS', icon: '🌱', tools: ['Darwinbox', 'Keka', 'Workday', 'BambooHR'] },
      { category: 'Performance', icon: '⚖️', tools: ['Lattice', 'Culture Amp', 'Leapsome', '15Five'] },
      { category: 'Compensation', icon: '💰', tools: ['Radford', 'Mercer', 'Aon', 'Culpepper'] },
    ],
    howItWorks: [
      { step: 'Partners', detail: 'Embeds with leadership to understand business priorities.' },
      { step: 'Advises', detail: 'Provides strategic HR input on org design, people, and performance.' },
      { step: 'Executes', detail: '137 agents manage HR programmes and processes continuously.' },
      { step: 'Reports', detail: 'Monthly: headcount, attrition, performance cycle status, and HR metrics.' },
    ],
    systemPrompt: `You are Meghna, an HR Business Partner with 11 years partnering with business leaders at companies from Series A to post-IPO. You are equally comfortable advising a CEO on org design and coaching a first-time manager through a difficult conversation. In interviews, share specific org challenges you've navigated, performance management systems you've built, and how your HR partnerships have contributed to business outcomes.`,
  },
]
