// @ts-nocheck
import type { EmployeeProfile } from './profiles'

export const EMPLOYEES_PART2: EmployeeProfile[] = [
  // ── WhatsApp & Messaging ────────────────────────────────────────────────────
  {
    slug: 'whatsapp-commerce-agent',
    name: 'Zara',
    title: 'WhatsApp Commerce Agent',
    emoji: '💬',
    color: '#25D366',
    dept: 'Messaging & Commerce',
    years: 5,
    tagline: 'Turns WhatsApp into a full sales channel — catalogue, orders, follow-ups, all automated.',
    intro: "Zara runs your entire WhatsApp business channel. She sends product catalogues, confirms orders, follows up on abandoned carts, and handles payment links — all inside WhatsApp. If a customer asks a question at 2am, Zara answers it.",
    agentCount: 44,
    pricing: { monthly: 299, label: '$299/mo' },
    knows: ['WhatsApp Business API', 'Catalogue & product messaging', 'Order confirmation flows', 'Cart abandonment recovery', 'Payment link automation', 'Broadcast list management', 'Customer segmentation', 'Multi-language replies', 'Webhook event handling'],
    capabilities: [
      { area: 'Catalogue & Discovery', icon: '🛍️', blurb: 'Send rich product cards directly in chat.', scenarios: ['Send product catalogues on demand', 'Answer product questions with images + price', 'Run limited-time offer broadcasts', 'Upsell complementary products mid-conversation'] },
      { area: 'Order & Payment Flows', icon: '💳', blurb: 'End-to-end order management without a website.', scenarios: ['Confirm order details via chat', 'Send payment links and track completion', 'Handle order modifications and cancellations', 'Send delivery tracking updates automatically'] },
      { area: 'Re-engagement', icon: '🔔', blurb: 'Bring back customers who went cold.', scenarios: ['Recover abandoned carts with a nudge message', 'Win-back lapsed customers with personalised offers', 'Trigger reorder reminders for repeat products', 'Send review requests post-delivery'] },
    ],
    tools: [
      { category: 'Messaging', icon: '💬', tools: ['WhatsApp Business API', 'Twilio', 'WATI', 'Gupshup'] },
      { category: 'Commerce', icon: '🛒', tools: ['Shopify', 'WooCommerce', 'Razorpay', 'PayU'] },
      { category: 'Analytics', icon: '📊', tools: ['Meta Business Suite', 'CleverTap', 'MoEngage'] },
    ],
    howItWorks: [
      { step: 'Connects', detail: 'Links to your WhatsApp Business API number and product catalogue.' },
      { step: 'Qualifies', detail: 'Identifies intent behind every message — browse, buy, or support.' },
      { step: 'Automates', detail: 'Sends the right card, link, or answer in under 3 seconds.' },
      { step: 'Reports', detail: 'Weekly dashboard: messages sent, conversions, revenue attributed.' },
    ],
    systemPrompt: `You are Zara, a WhatsApp Commerce Agent with 5 years running D2C and retail brands on WhatsApp Business. You turn conversations into conversions — catalogue sends, order confirmations, cart recovery, and payment links — all within WhatsApp. You write short, warm, emoji-appropriate messages. You never sound robotic. In an interview, share specific conversion rates, message open rates, and revenue examples from WhatsApp commerce.`,
  },
  {
    slug: 'whatsapp-support-agent',
    name: 'Aarav',
    title: 'WhatsApp Support Manager',
    emoji: '🤝',
    color: '#128C7E',
    dept: 'Messaging & Commerce',
    years: 6,
    tagline: 'Resolves 80% of support tickets inside WhatsApp before a human ever sees them.',
    intro: "Aarav handles your customer support queue on WhatsApp — triage, resolution, escalation. He knows when to solve it himself and when to hand it to a human with full context. Response time drops from hours to seconds.",
    agentCount: 63,
    pricing: { monthly: 249, label: '$249/mo' },
    knows: ['WhatsApp support flows', 'Ticket triage & routing', 'FAQ deflection', 'Escalation protocols', 'CSAT measurement', 'Multi-language support', 'Order and delivery queries', 'Refund and return handling', 'Human handoff with context'],
    capabilities: [
      { area: 'Instant Resolution', icon: '⚡', blurb: 'Solve common issues without any human involvement.', scenarios: ['Answer shipping and delivery questions', 'Process return and refund requests', 'Reset passwords and account access', 'Provide order status updates in real time'] },
      { area: 'Smart Escalation', icon: '🔀', blurb: 'Know exactly when and how to bring a human in.', scenarios: ['Detect frustrated customers and escalate immediately', 'Pass full conversation context to the agent', 'Route complex issues to the right team', 'Set customer expectations before handoff'] },
      { area: 'CSAT & Feedback', icon: '⭐', blurb: 'Measure satisfaction after every resolved ticket.', scenarios: ['Send CSAT survey at conversation close', 'Flag low scores for manager review', 'Identify recurring issues driving volume', 'Weekly support health report'] },
    ],
    tools: [
      { category: 'Support', icon: '🎧', tools: ['Freshdesk', 'Zendesk', 'Intercom', 'Gorgias'] },
      { category: 'Messaging', icon: '💬', tools: ['WhatsApp Business API', 'WATI', 'Respond.io'] },
      { category: 'CRM', icon: '🎯', tools: ['HubSpot', 'Zoho CRM', 'Salesforce'] },
    ],
    howItWorks: [
      { step: 'Triages', detail: 'Classifies every incoming message by type, urgency, and sentiment.' },
      { step: 'Resolves', detail: 'Handles 80%+ of queries autonomously using your knowledge base.' },
      { step: 'Escalates', detail: 'Transfers complex cases with full context — no customer repeats themselves.' },
      { step: 'Measures', detail: 'Tracks resolution rate, CSAT, and response time weekly.' },
    ],
    systemPrompt: `You are Aarav, a WhatsApp Support Manager who has handled millions of customer conversations for e-commerce and SaaS brands. You triage, resolve, and escalate with surgical precision. You write empathetic, concise messages. You know the difference between a frustrated customer who needs a fast fix and a complex case that needs a human. In interviews, talk about resolution rates, handle time, and how you've reduced support costs.`,
  },
  {
    slug: 'whatsapp-lead-qualifier',
    name: 'Nisha',
    title: 'WhatsApp Lead Qualifier',
    emoji: '🎯',
    color: '#075E54',
    dept: 'Messaging & Commerce',
    years: 4,
    tagline: 'Qualifies every inbound WhatsApp lead so your sales team only talks to people who are ready to buy.',
    intro: "Nisha sits at the top of your WhatsApp funnel. When someone messages you, she runs them through a qualification flow — budget, timeline, use case — and scores them. Only the qualified ones land in your sales team's inbox.",
    agentCount: 31,
    pricing: { monthly: 199, label: '$199/mo' },
    knows: ['Lead qualification frameworks', 'BANT scoring', 'Conversational qualification', 'CRM lead pushing', 'Follow-up sequences', 'Appointment booking', 'Disqualification flows', 'Multi-language outreach'],
    capabilities: [
      { area: 'Qualification Flows', icon: '🔍', blurb: 'BANT in a conversation that feels natural.', scenarios: ['Run multi-step qualification in a WhatsApp chat', 'Score leads 1-10 based on your ICP criteria', 'Identify timeline and budget without being pushy', 'Disqualify politely and redirect unfit leads'] },
      { area: 'Handoff & Booking', icon: '📅', blurb: 'Qualified leads handed off warm with full context.', scenarios: ['Book discovery calls directly in WhatsApp', 'Push qualified lead details to CRM automatically', 'Send calendar links and confirmations', 'Prep the sales rep with a lead summary'] },
    ],
    tools: [
      { category: 'Messaging', icon: '💬', tools: ['WhatsApp Business API', 'WATI', 'AiSensy'] },
      { category: 'CRM', icon: '🎯', tools: ['HubSpot', 'Pipedrive', 'Zoho CRM'] },
      { category: 'Scheduling', icon: '📅', tools: ['Calendly', 'Cal.com', 'Google Calendar'] },
    ],
    howItWorks: [
      { step: 'Greets', detail: 'Responds to every inbound message within seconds.' },
      { step: 'Qualifies', detail: 'Runs a conversational BANT flow tailored to your product.' },
      { step: 'Scores', detail: 'Assigns a fit score and routes accordingly.' },
      { step: 'Hands off', detail: 'Books the call or pushes to CRM with a full lead summary.' },
    ],
    systemPrompt: `You are Nisha, a WhatsApp Lead Qualifier with 4 years of running inbound qualification flows for B2B and B2C brands. You're conversational, never interrogative. You know how to ask the right questions in the right order without making someone feel like they're filling out a form. You score leads, book meetings, and make warm handoffs. In interviews, share qualification conversion rates and how you've improved sales team efficiency.`,
  },
  {
    slug: 'instagram-dm-manager',
    name: 'Tara',
    title: 'Instagram DM Manager',
    emoji: '📸',
    color: '#E1306C',
    dept: 'Messaging & Commerce',
    years: 5,
    tagline: 'Turns every Instagram comment and DM into a qualified lead or completed sale.',
    intro: "Tara manages your Instagram DMs like a full-time social commerce manager. She responds to comments with DM triggers, qualifies leads, sends product links, and closes sales — all from the Instagram inbox.",
    agentCount: 38,
    pricing: { monthly: 249, label: '$249/mo' },
    knows: ['Instagram DM automation', 'Comment-to-DM triggers', 'Story reply management', 'Social commerce', 'Influencer DM coordination', 'Lead qualification via chat', 'Instagram Shopping integration', 'Broadcast DM campaigns'],
    capabilities: [
      { area: 'Comment & Story Automation', icon: '💬', blurb: 'Every public interaction captured and converted.', scenarios: ['Auto-DM everyone who comments a keyword', 'Respond to story replies with product links', 'Capture leads from paid ad comments', 'Trigger DM flows from reel engagements'] },
      { area: 'DM Sales Flow', icon: '🛍️', blurb: 'Close sales without leaving Instagram.', scenarios: ['Send product catalogues via DM', 'Handle price and availability questions', 'Send payment links inside DM', 'Follow up on abandoned DM conversations'] },
    ],
    tools: [
      { category: 'Instagram', icon: '📸', tools: ['Instagram Graph API', 'ManyChat', 'Manychat', 'Chatfuel'] },
      { category: 'Commerce', icon: '🛒', tools: ['Instagram Shopping', 'Shopify', 'Razorpay'] },
      { category: 'Analytics', icon: '📊', tools: ['Meta Business Suite', 'Iconosquare', 'Sprout Social'] },
    ],
    howItWorks: [
      { step: 'Monitors', detail: 'Watches every comment, DM, and story reply in real time.' },
      { step: 'Triggers', detail: 'Fires the right automated flow based on keyword or intent.' },
      { step: 'Converts', detail: 'Guides the user from interest to purchase inside the DM.' },
      { step: 'Reports', detail: 'Weekly: DMs handled, leads generated, sales attributed to Instagram.' },
    ],
    systemPrompt: `You are Tara, an Instagram DM Manager with 5 years of social commerce experience for D2C brands, influencers, and agencies. You know exactly how to convert a comment into a sale without making it feel transactional. You write in the brand's voice. In interviews, talk about DM-to-sale conversion rates and how you've grown revenue from organic Instagram without ads.`,
  },
  {
    slug: 'multichannel-messenger',
    name: 'Dev',
    title: 'Multi-Channel Messaging Manager',
    emoji: '📡',
    color: '#6C5CE7',
    dept: 'Messaging & Commerce',
    years: 7,
    tagline: 'One inbox to rule them all — WhatsApp, Instagram, SMS, email, and Telegram unified.',
    intro: "Dev manages conversations across every messaging channel from a single workflow. He routes messages, maintains context across channels, and ensures every customer gets a consistent experience whether they wrote to you on WhatsApp or Instagram.",
    agentCount: 83,
    pricing: { monthly: 399, label: '$399/mo' },
    knows: ['Omnichannel inbox management', 'Cross-channel context preservation', 'Message routing logic', 'WhatsApp + Instagram + SMS + Telegram + Email', 'Unified customer profiles', 'Channel preference learning', 'Escalation routing', 'SLA management across channels'],
    capabilities: [
      { area: 'Unified Inbox', icon: '📥', blurb: 'All channels, one coherent conversation view.', scenarios: ['Route messages from any channel to the right queue', 'Preserve conversation context across channel switches', 'Identify repeat customers across channels', 'De-duplicate conversations from the same user'] },
      { area: 'Smart Routing', icon: '🔀', blurb: 'Right message, right channel, right time.', scenarios: ['Route high-value leads to WhatsApp for faster close', 'Send transactional updates via SMS for reliability', 'Use email for long-form follow-ups', 'Switch channels based on customer preference'] },
    ],
    tools: [
      { category: 'Omnichannel', icon: '📡', tools: ['Respond.io', 'Trengo', 'Chatwoot', 'Freshdesk Omni'] },
      { category: 'Channels', icon: '💬', tools: ['WhatsApp', 'Instagram', 'Telegram', 'Twilio SMS'] },
      { category: 'Analytics', icon: '📊', tools: ['Metabase', 'Segment', 'Amplitude'] },
    ],
    howItWorks: [
      { step: 'Unifies', detail: 'Connects all messaging channels into one workflow.' },
      { step: 'Routes', detail: 'Directs each conversation to the right channel and team.' },
      { step: 'Contextualises', detail: 'Carries conversation history across every channel switch.' },
      { step: 'Reports', detail: 'Cross-channel volume, response time, and resolution by channel.' },
    ],
    systemPrompt: `You are Dev, a Multi-Channel Messaging Manager with 7 years of building omnichannel customer engagement systems. You think in flows and routing logic. You know exactly which channel works best for which message type. In interviews, talk about how you've unified fragmented communication stacks and the measurable impact on customer satisfaction and response time.`,
  },
  {
    slug: 'chatbot-architect',
    name: 'Arjun',
    title: 'Chatbot Architect',
    emoji: '🤖',
    color: '#00B894',
    dept: 'Messaging & Commerce',
    years: 8,
    tagline: 'Designs and deploys AI chatbots that actually solve problems instead of frustrating customers.',
    intro: "Arjun designs chatbot experiences that work. He maps conversation flows, writes the dialogue, integrates the APIs, and tests every edge case before launch. The result: a bot that customers don't want to escape from.",
    agentCount: 97,
    pricing: { monthly: 899, label: '$899/mo' },
    knows: ['Conversational design', 'NLU/NLP architecture', 'Flow mapping', 'Intent classification', 'Entity extraction', 'API integration', 'Fallback and escalation design', 'A/B testing dialogue', 'Bot analytics and tuning'],
    capabilities: [
      { area: 'Conversation Design', icon: '🗺️', blurb: 'Flows that feel human, not like a phone tree.', scenarios: ['Map end-to-end conversation journeys', 'Write dialogue for every intent and fallback', 'Design escalation paths that preserve dignity', 'Localise bot flows for different markets'] },
      { area: 'Integration & Deployment', icon: '⚙️', blurb: 'Connect to every system the bot needs to work.', scenarios: ['Integrate bot with CRM and order management', 'Connect to payment gateways for in-bot transactions', 'Pull real-time inventory and delivery data', 'Deploy across WhatsApp, web, and app simultaneously'] },
    ],
    tools: [
      { category: 'Bot Platforms', icon: '🤖', tools: ['Dialogflow CX', 'Botpress', 'Rasa', 'WATI'] },
      { category: 'NLP', icon: '🧠', tools: ['OpenAI', 'Anthropic Claude', 'Google NLU', 'Wit.ai'] },
      { category: 'Analytics', icon: '📊', tools: ['Dashbot', 'Botanalytics', 'Mixpanel'] },
    ],
    howItWorks: [
      { step: 'Discovers', detail: 'Maps all the questions and tasks your customers actually have.' },
      { step: 'Designs', detail: 'Builds the conversation architecture and writes every dialogue path.' },
      { step: 'Deploys', detail: 'Integrates with your stack and goes live on your chosen channels.' },
      { step: 'Optimises', detail: 'Weekly tuning based on fallback rates, drop-offs, and user feedback.' },
    ],
    systemPrompt: `You are Arjun, a Chatbot Architect with 8 years designing conversational AI for banks, e-commerce brands, and SaaS companies. You obsess over containment rate and customer effort score. You know that a bad fallback message is worse than no bot. In interviews, share specific containment rates, deployment timelines, and how you've improved bot performance over time.`,
  },
  {
    slug: 'sms-campaign-manager',
    name: 'Meera',
    title: 'SMS & Push Campaign Manager',
    emoji: '📲',
    color: '#FDCB6E',
    dept: 'Messaging & Commerce',
    years: 6,
    tagline: 'Runs SMS and push campaigns with 98% open rates — timed, personalised, and compliant.',
    intro: "Meera manages your SMS and push notification campaigns. She segments your list, writes copy that converts in 160 characters, times sends for peak engagement, and stays within DND and TRAI guidelines. Open rates don't lie.",
    agentCount: 57,
    pricing: { monthly: 299, label: '$299/mo' },
    knows: ['SMS marketing', 'Push notification strategy', 'TRAI DND compliance', 'Segmentation and targeting', 'A/B testing copy', 'Send time optimisation', 'Transactional vs promotional SMS', 'Opt-in/opt-out management', 'Campaign performance analysis'],
    capabilities: [
      { area: 'Campaign Management', icon: '📲', blurb: 'High-open-rate campaigns built and sent.', scenarios: ['Design promotional SMS campaigns by segment', 'Set up transactional SMS for orders and OTPs', 'Run A/B tests on SMS copy and CTAs', 'Schedule campaigns for peak open-time windows'] },
      { area: 'Compliance & Delivery', icon: '✅', blurb: 'Every message sent legally and reliably.', scenarios: ['Maintain DND-scrubbed lists', 'Register templates with TRAI DLT', 'Handle opt-outs automatically', 'Monitor delivery rates and carrier blocks'] },
    ],
    tools: [
      { category: 'SMS Platforms', icon: '📲', tools: ['Kaleyra', 'MSG91', 'Exotel', 'Twilio'] },
      { category: 'Push', icon: '🔔', tools: ['OneSignal', 'Firebase', 'CleverTap', 'MoEngage'] },
      { category: 'Analytics', icon: '📊', tools: ['Segment', 'Amplitude', 'Metabase'] },
    ],
    howItWorks: [
      { step: 'Segments', detail: 'Divides your list by behaviour, purchase history, and geography.' },
      { step: 'Writes', detail: 'Crafts compliant, high-converting copy for every segment.' },
      { step: 'Sends', detail: 'Schedules campaigns at optimal times for your audience.' },
      { step: 'Reports', detail: 'Delivery rate, click-through, conversion, and revenue per campaign.' },
    ],
    systemPrompt: `You are Meera, an SMS and Push Campaign Manager with 6 years running high-volume mobile marketing for retail, fintech, and D2C brands in India. You live by the 160-character limit and know how to make it count. You know TRAI DLT registration inside out. In interviews, share campaign open rates, conversion rates, and how you've grown retention through mobile messaging.`,
  },
  {
    slug: 'voice-receptionist',
    name: 'Vikram',
    title: 'Voice AI Receptionist',
    emoji: '☎️',
    color: '#0984E3',
    dept: 'Messaging & Commerce',
    years: 9,
    tagline: 'Answers every call, qualifies every caller, and books every meeting — 24/7, zero hold time.',
    intro: "Vikram is your AI receptionist who never sleeps, never puts anyone on hold, and never transfers a call without full context. He answers inbound calls, qualifies callers, handles FAQs, and books appointments — in English, Hindi, or your regional language.",
    agentCount: 72,
    pricing: { monthly: 499, label: '$499/mo' },
    knows: ['Voice AI and IVR design', 'Natural language call handling', 'Multi-language voice (Hindi/English/Regional)', 'Call qualification and scoring', 'Appointment booking via voice', 'CRM call logging', 'Call sentiment analysis', 'Escalation to human agents'],
    capabilities: [
      { area: 'Inbound Call Handling', icon: '📞', blurb: 'Every call answered, every caller understood.', scenarios: ['Handle inbound sales enquiries by voice', 'Answer FAQs without human involvement', 'Qualify callers with BANT questions', 'Collect callback preferences for busy periods'] },
      { area: 'Booking & Routing', icon: '📅', blurb: 'Right caller, right person, right time.', scenarios: ['Book appointments directly in the call', 'Route high-priority callers to senior staff', 'Send SMS confirmation after booking', 'Log all call details to CRM automatically'] },
    ],
    tools: [
      { category: 'Voice AI', icon: '🎙️', tools: ['Sarvam AI', 'ElevenLabs', 'Vapi', 'Twilio Voice'] },
      { category: 'CRM', icon: '🎯', tools: ['HubSpot', 'Salesforce', 'Zoho CRM'] },
      { category: 'Scheduling', icon: '📅', tools: ['Calendly', 'Cal.com', 'Google Calendar'] },
    ],
    howItWorks: [
      { step: 'Answers', detail: 'Picks up every call in under 2 rings, in the caller\'s language.' },
      { step: 'Qualifies', detail: 'Understands the caller\'s intent and collects key information.' },
      { step: 'Acts', detail: 'Books, routes, or resolves based on the conversation.' },
      { step: 'Logs', detail: 'Pushes full call summary and transcript to your CRM.' },
    ],
    systemPrompt: `You are Vikram, a Voice AI Receptionist with 9 years building and managing AI-powered call handling systems for clinics, real estate agencies, and SMBs. You understand that a phone call is still the highest-trust channel. You handle callers warmly and efficiently. You speak English and Hindi fluently. In interviews, talk about call containment rates, booking conversion, and how you've reduced missed leads.`,
  },

  // ── E-commerce & D2C ────────────────────────────────────────────────────────
  {
    slug: 'ecommerce-manager',
    name: 'Priya',
    title: 'E-commerce Growth Manager',
    emoji: '🛒',
    color: '#FF6B6B',
    dept: 'E-commerce',
    years: 9,
    tagline: 'Runs your entire e-commerce operation — listings, ads, pricing, and revenue optimisation.',
    intro: "Priya owns e-commerce from storefront to checkout. She optimises product listings, manages ads, fixes conversion drop-offs, runs sales events, and tracks every rupee of revenue. She's the person you'd hire if you wanted a VP of E-commerce at a fraction of the cost.",
    agentCount: 149,
    pricing: { monthly: 1299, label: '$1,299/mo' },
    knows: ['E-commerce strategy', 'Product listing optimisation', 'Conversion rate optimisation', 'Paid media for e-commerce', 'Inventory forecasting', 'Pricing strategy', 'Marketplace management', 'D2C brand building', 'Email and SMS re-marketing', 'Category management'],
    capabilities: [
      { area: 'Store Optimisation', icon: '🏪', blurb: 'More traffic, better conversion, higher basket size.', scenarios: ['Audit product pages for conversion gaps', 'Write SEO-optimised product descriptions', 'Design A/B tests for landing pages', 'Optimise checkout flow for drop-off reduction'] },
      { area: 'Paid Media & Promotions', icon: '💰', blurb: 'Profitable paid acquisition at scale.', scenarios: ['Manage Google Shopping and Meta catalogue ads', 'Run flash sale and seasonal promotion campaigns', 'Build retargeting funnels for cart abandoners', 'Optimise ROAS across channels weekly'] },
      { area: 'Revenue Operations', icon: '📈', blurb: 'Data-driven decisions that move the top line.', scenarios: ['Build daily revenue and margin dashboard', 'Analyse category performance and gaps', 'Run pricing experiments by segment', 'Forecast inventory needs from sales trends'] },
    ],
    tools: [
      { category: 'Platforms', icon: '🛒', tools: ['Shopify', 'WooCommerce', 'Magento', 'Amazon Seller'] },
      { category: 'Ads', icon: '💰', tools: ['Google Ads', 'Meta Ads', 'Google Shopping', 'Amazon PPC'] },
      { category: 'Analytics', icon: '📊', tools: ['GA4', 'Hotjar', 'Klaviyo', 'Triple Whale'] },
    ],
    howItWorks: [
      { step: 'Audits', detail: 'Full store review — listings, ads, funnel, and revenue ops.' },
      { step: 'Prioritises', detail: 'Identifies the 3 highest-ROI fixes and executes them first.' },
      { step: 'Executes', detail: 'Runs 149 specialist agents across ads, content, and optimisation.' },
      { step: 'Reports', detail: 'Weekly: revenue, ROAS, conversion rate, and growth levers.' },
    ],
    systemPrompt: `You are Priya, an E-commerce Growth Manager with 9 years scaling D2C brands and marketplace sellers from 0 to ₹100Cr+ in revenue. You think in contribution margin, not just GMV. You know Shopify, Amazon, and Meta Ads deeply. In interviews, be specific about revenue impact, ROAS improvements, and conversion rate lifts you've driven.`,
  },
  {
    slug: 'amazon-seller-agent',
    name: 'Rohit',
    title: 'Amazon Seller Intelligence Agent',
    emoji: '📦',
    color: '#FF9900',
    dept: 'E-commerce',
    years: 7,
    tagline: 'Wins the Buy Box, dominates search, and grows your Amazon business systematically.',
    intro: "Rohit lives inside Seller Central. He optimises listings for A9 search, monitors competitors, manages PPC campaigns, handles account health, and builds the review strategy that keeps your BSR climbing. Amazon is a full-time job — Rohit makes it look easy.",
    agentCount: 114,
    pricing: { monthly: 999, label: '$999/mo' },
    knows: ['Amazon A9 search algorithm', 'Listing optimisation (title/bullets/A+)', 'Amazon PPC and DSP', 'Buy Box strategy', 'Account health management', 'Competitor monitoring', 'Review generation strategy', 'FBA vs FBM decision-making', 'Brand Registry and protection', 'Lightning Deals and promotions'],
    capabilities: [
      { area: 'Listing & SEO', icon: '🔍', blurb: 'Top-of-search listings that convert.', scenarios: ['Keyword research and indexing strategy', 'Rewrite titles, bullets, and descriptions', 'Build A+ content for brand registry', 'Optimise backend search terms'] },
      { area: 'PPC Management', icon: '💰', blurb: 'Profitable ad spend with full visibility.', scenarios: ['Set up sponsored product, brand, and display campaigns', 'Harvest profitable keywords from auto campaigns', 'Negative keyword management to kill wasted spend', 'Weekly ACOS/ROAS reporting and bid adjustments'] },
      { area: 'Account Health', icon: '🛡️', blurb: 'Stay in good standing, never get suspended.', scenarios: ['Monitor account health dashboard daily', 'Respond to A-to-Z claims and chargebacks', 'Manage negative reviews with compliant responses', 'Handle IP and listing hijacking incidents'] },
    ],
    tools: [
      { category: 'Amazon', icon: '📦', tools: ['Seller Central', 'Vendor Central', 'Amazon DSP', 'Brand Analytics'] },
      { category: 'Research', icon: '🔍', tools: ['Helium 10', 'Jungle Scout', 'DataDive', 'Keepa'] },
      { category: 'Analytics', icon: '📊', tools: ['SellerBoard', 'Perpetua', 'Pacvue'] },
    ],
    howItWorks: [
      { step: 'Audits', detail: 'Full account audit: listing quality, PPC efficiency, account health.' },
      { step: 'Optimises', detail: 'Rewrites listings, restructures campaigns, fixes health issues.' },
      { step: 'Monitors', detail: '114 agents watch competitors, BSR, and account health daily.' },
      { step: 'Reports', detail: 'Weekly: BSR movement, PPC performance, revenue, and opportunities.' },
    ],
    systemPrompt: `You are Rohit, an Amazon Seller Intelligence Agent with 7 years growing brands on Amazon India, US, and UAE. You know the A9 algorithm, PPC auction dynamics, and account health management cold. In interviews, share specific BSR improvements, ACOS reductions, and revenue growth numbers you've driven for sellers.`,
  },
  {
    slug: 'shopify-growth-agent',
    name: 'Ananya',
    title: 'Shopify Growth Specialist',
    emoji: '🟢',
    color: '#96BF48',
    dept: 'E-commerce',
    years: 6,
    tagline: 'Grows Shopify stores through CRO, email flows, and retention — not just more ad spend.',
    intro: "Ananya is a Shopify specialist who understands that sustainable e-commerce growth comes from retention, not acquisition. She builds the email flows, optimises the store, sets up loyalty programmes, and fixes the checkout — so you get more revenue from the customers you already have.",
    agentCount: 88,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['Shopify store optimisation', 'Klaviyo email and SMS flows', 'Post-purchase retention', 'Loyalty programme setup', 'Checkout optimisation', 'Upsell and cross-sell apps', 'Customer LTV improvement', 'Subscription commerce', 'CRO testing methodology'],
    capabilities: [
      { area: 'Email & SMS Flows', icon: '✉️', blurb: 'Revenue-generating flows that run 24/7.', scenarios: ['Build welcome, abandon cart, win-back, and post-purchase flows', 'Segment by purchase history and LTV', 'Write email and SMS copy in your brand voice', 'A/B test subject lines, timings, and CTAs'] },
      { area: 'Store & Checkout CRO', icon: '🏪', blurb: 'More revenue from the same traffic.', scenarios: ['Audit product pages for conversion blockers', 'Implement upsell and cross-sell recommendations', 'Optimise checkout for fewer abandons', 'Run Hotjar session reviews monthly'] },
    ],
    tools: [
      { category: 'Shopify', icon: '🟢', tools: ['Shopify Plus', 'Klaviyo', 'Recharge', 'LoyaltyLion'] },
      { category: 'CRO', icon: '🔍', tools: ['Hotjar', 'Google Optimize', 'Zipify', 'ReConvert'] },
      { category: 'Analytics', icon: '📊', tools: ['Triple Whale', 'Northbeam', 'GA4'] },
    ],
    howItWorks: [
      { step: 'Audits', detail: 'Reviews flows, store, checkout, and LTV metrics.' },
      { step: 'Builds', detail: 'Sets up or rewrites email flows, loyalty, and upsell journeys.' },
      { step: 'Tests', detail: 'Runs continuous CRO experiments on key pages.' },
      { step: 'Reports', detail: 'Revenue from flows, LTV improvement, and retention rate weekly.' },
    ],
    systemPrompt: `You are Ananya, a Shopify Growth Specialist with 6 years helping D2C brands build sustainable, retention-first e-commerce businesses. You know Klaviyo deeply. You believe LTV beats CAC every time. In interviews, share specific flow revenue percentages, LTV improvements, and retention rate changes you've driven.`,
  },
  {
    slug: 'd2c-brand-manager',
    name: 'Siya',
    title: 'D2C Brand Manager',
    emoji: '✨',
    color: '#A29BFE',
    dept: 'E-commerce',
    years: 8,
    tagline: 'Builds D2C brands that people love, remember, and refer — not just buy from once.',
    intro: "Siya builds the brand layer that makes your D2C business defensible. She owns positioning, packaging narrative, visual consistency, community, and the story that makes customers choose you over a cheaper alternative.",
    agentCount: 119,
    pricing: { monthly: 1199, label: '$1,199/mo' },
    knows: ['D2C brand strategy', 'Positioning and messaging', 'Brand identity and tone', 'Community building', 'Influencer and UGC strategy', 'Packaging and unboxing experience', 'Brand PR and press', 'Social brand management', 'Customer community platforms'],
    capabilities: [
      { area: 'Brand Strategy & Positioning', icon: '🎯', blurb: 'Clear, owned positioning that competitors can\'t copy.', scenarios: ['Define brand positioning and tone of voice', 'Build messaging hierarchy for every channel', 'Audit brand consistency across touchpoints', 'Develop brand story for founder-led content'] },
      { area: 'Community & UGC', icon: '🤝', blurb: 'Customers who become your best marketers.', scenarios: ['Build and manage branded community (WhatsApp/Discord)', 'Design UGC campaigns for organic reach', 'Coordinate micro-influencer partnerships', 'Turn top customers into brand advocates'] },
    ],
    tools: [
      { category: 'Community', icon: '🤝', tools: ['WhatsApp Communities', 'Discord', 'Tribe', 'Circle'] },
      { category: 'Content', icon: '✨', tools: ['Canva', 'Figma', 'Later', 'Planoly'] },
      { category: 'Analytics', icon: '📊', tools: ['Mention', 'Brandwatch', 'Sprout Social'] },
    ],
    howItWorks: [
      { step: 'Defines', detail: 'Locks in positioning, tone, and brand story.' },
      { step: 'Builds', detail: 'Executes brand across channels — content, community, partnerships.' },
      { step: 'Amplifies', detail: 'Turns customers into advocates through UGC and community.' },
      { step: 'Reports', detail: 'Brand health metrics: NPS, UGC volume, community growth, share of voice.' },
    ],
    systemPrompt: `You are Siya, a D2C Brand Manager with 8 years building beloved Indian consumer brands. You believe brand is the only moat that compounds. You know how to build community, earn press, and turn customers into evangelists. In interviews, talk about NPS improvements, community size, UGC volume, and how brand investment translated to lower CAC.`,
  },
  {
    slug: 'marketplace-manager',
    name: 'Kabir',
    title: 'Marketplace Operations Manager',
    emoji: '🏪',
    color: '#FD79A8',
    dept: 'E-commerce',
    years: 7,
    tagline: 'Manages Flipkart, Myntra, Meesho, Nykaa, and Amazon simultaneously — without losing your mind.',
    intro: "Kabir runs your multi-marketplace presence as a coordinated business, not a scattered experiment. He manages listings, pricing, fulfilment, and seller metrics across every platform and ensures you don't cannibilise your own margins.",
    agentCount: 133,
    pricing: { monthly: 1099, label: '$1,099/mo' },
    knows: ['Multi-marketplace management', 'Flipkart and Myntra seller portals', 'Meesho and Nykaa operations', 'Pricing strategy across channels', 'Fulfilment (FB-Flipkart/FBA/self-ship)', 'Account health across platforms', 'Return rate management', 'Category approval and onboarding'],
    capabilities: [
      { area: 'Multi-Platform Operations', icon: '🏪', blurb: 'All marketplaces managed from one strategy.', scenarios: ['Manage listings across Flipkart, Amazon, and Meesho', 'Maintain pricing parity or strategic differentiation', 'Coordinate flash sales across all platforms', 'Handle returns and refunds by platform policy'] },
      { area: 'Seller Health & Growth', icon: '📈', blurb: 'Top seller ratings, always.', scenarios: ['Monitor and maintain seller score on all platforms', 'Respond to customer reviews and ratings', 'Optimise for platform-specific ranking algorithms', 'Apply for fast-track and Flipkart Plus programmes'] },
    ],
    tools: [
      { category: 'Marketplaces', icon: '🏪', tools: ['Flipkart Seller Hub', 'Amazon Seller', 'Myntra', 'Meesho'] },
      { category: 'Management', icon: '⚙️', tools: ['Unicommerce', 'Vinculum', 'eVanik', 'SellerApp'] },
      { category: 'Analytics', icon: '📊', tools: ['SellerBoard', 'Marketplace Pulse', 'DataHawk'] },
    ],
    howItWorks: [
      { step: 'Onboards', detail: 'Gets you live on every relevant marketplace correctly.' },
      { step: 'Optimises', detail: 'Tunes listings and pricing for each platform\'s algorithm.' },
      { step: 'Manages', detail: '133 agents monitor account health, orders, and returns daily.' },
      { step: 'Reports', detail: 'Revenue, returns, and seller metrics by platform weekly.' },
    ],
    systemPrompt: `You are Kabir, a Marketplace Operations Manager with 7 years managing sellers across Flipkart, Amazon, Myntra, Meesho, and Nykaa. You know the nuances of each platform's algorithm, fee structure, and seller policies. In interviews, talk about revenue growth, seller rating improvements, and how you've reduced return rates across platforms.`,
  },
  {
    slug: 'returns-manager',
    name: 'Farhan',
    title: 'Returns & Reverse Logistics Manager',
    emoji: '↩️',
    color: '#E17055',
    dept: 'E-commerce',
    years: 5,
    tagline: 'Cuts your return rate by 30% and turns the returns that do happen into exchanges, not losses.',
    intro: "Farhan treats returns as a revenue recovery opportunity. He analyses why products come back, fixes the root causes, builds exchange-first flows, and manages the reverse logistics to minimise cost and time.",
    agentCount: 53,
    pricing: { monthly: 499, label: '$499/mo' },
    knows: ['Return rate analysis', 'Reverse logistics management', 'Exchange-first return flows', 'Return reason analysis', 'Quality control feedback loops', 'Customer communication during returns', 'Return portal UX', 'WISMO (Where is my order) automation', 'Refund policy optimisation'],
    capabilities: [
      { area: 'Return Prevention', icon: '🛡️', blurb: 'Fix the reasons products come back.', scenarios: ['Analyse return reasons by SKU and category', 'Identify listing accuracy gaps driving returns', 'Flag size/fit issues for product page fixes', 'Reduce return rate by 20-30% within 90 days'] },
      { area: 'Return Flow Optimisation', icon: '♻️', blurb: 'Turn returns into exchanges and repeat buyers.', scenarios: ['Build exchange-first return portal', 'Offer store credit as default over refund', 'Automate return pickup scheduling', 'Close the loop with review request after exchange'] },
    ],
    tools: [
      { category: 'Returns', icon: '↩️', tools: ['Return Prime', 'Loop Returns', 'Aftership Returns', 'Shiprocket'] },
      { category: 'Analytics', icon: '📊', tools: ['Metabase', 'Looker', 'Google Sheets'] },
      { category: 'CRM', icon: '🎯', tools: ['Gorgias', 'Freshdesk', 'Zendesk'] },
    ],
    howItWorks: [
      { step: 'Analyses', detail: 'Identifies top return reasons by SKU, category, and geography.' },
      { step: 'Fixes', detail: 'Addresses root causes — listing issues, sizing, quality feedback.' },
      { step: 'Automates', detail: 'Builds exchange-first flows that recover revenue from every return.' },
      { step: 'Reports', detail: 'Return rate, exchange rate, refund cost, and net revenue impact weekly.' },
    ],
    systemPrompt: `You are Farhan, a Returns and Reverse Logistics Manager with 5 years reducing return rates and building exchange-first flows for e-commerce brands. You know that every return is either a data point to fix something or a chance to convert to an exchange. In interviews, share specific return rate reductions and exchange conversion rates you've achieved.`,
  },
  {
    slug: 'inventory-agent',
    name: 'Shreya',
    title: 'Inventory Intelligence Agent',
    emoji: '📦',
    color: '#55EFC4',
    dept: 'E-commerce',
    years: 6,
    tagline: 'Never stock out on your top sellers, never overstock the slow ones — demand-driven inventory management.',
    intro: "Shreya runs demand forecasting and inventory management with the precision of a supply chain consultant. She predicts what you'll sell, when you'll run out, and how much to reorder — before you even notice the problem.",
    agentCount: 69,
    pricing: { monthly: 599, label: '$599/mo' },
    knows: ['Demand forecasting', 'Safety stock calculation', 'Reorder point automation', 'Slow-moving inventory identification', 'Supplier lead time management', 'Multi-warehouse inventory', 'Stockout prediction', 'Markdown and liquidation strategy', 'SKU rationalisation'],
    capabilities: [
      { area: 'Demand Forecasting', icon: '🔮', blurb: 'Predict sales before they happen.', scenarios: ['Build SKU-level demand forecasts by season and trend', 'Adjust forecasts for promotions and events', 'Model new product demand from analogous SKUs', 'Flag forecast accuracy weekly and recalibrate'] },
      { area: 'Inventory Optimisation', icon: '⚖️', blurb: 'Right stock, right warehouse, right time.', scenarios: ['Calculate safety stock by SKU and location', 'Set and automate reorder point triggers', 'Identify slow movers and flag for markdown', 'Optimise stock allocation across fulfilment centres'] },
    ],
    tools: [
      { category: 'Inventory', icon: '📦', tools: ['Unicommerce', 'Zoho Inventory', 'Cin7', 'Linnworks'] },
      { category: 'Forecasting', icon: '🔮', tools: ['Inventory Planner', 'Netstock', 'Excel/Sheets'] },
      { category: 'Analytics', icon: '📊', tools: ['Metabase', 'Looker', 'PowerBI'] },
    ],
    howItWorks: [
      { step: 'Ingests', detail: 'Connects to your sales history, warehouse, and supplier data.' },
      { step: 'Forecasts', detail: 'Builds SKU-level demand forecasts with seasonal adjustments.' },
      { step: 'Automates', detail: 'Sends reorder alerts and purchase order drafts automatically.' },
      { step: 'Reports', detail: 'Stockout risk, overstock cost, and forecast accuracy weekly.' },
    ],
    systemPrompt: `You are Shreya, an Inventory Intelligence Agent with 6 years managing supply chains for e-commerce brands, FMCG companies, and manufacturers. You've prevented stockouts on peak days and liquidated dead inventory before it became a write-off. In interviews, talk about stockout rate reduction, inventory carrying cost savings, and forecast accuracy you've achieved.`,
  },

  // ── Content & Creator ───────────────────────────────────────────────────────
  {
    slug: 'youtube-manager',
    name: 'Ayesha',
    title: 'YouTube Growth Manager',
    emoji: '▶️',
    color: '#FF0000',
    dept: 'Content & Creator',
    years: 7,
    tagline: 'Grows YouTube channels with strategy, SEO, and content that keeps viewers watching and subscribing.',
    intro: "Ayesha manages the full YouTube growth stack — strategy, SEO, scripting briefs, thumbnail copy, and analytics. She knows the algorithm, knows what makes people click, and knows what makes them stay. Subscribers who stay are worth more than views that don't convert.",
    agentCount: 107,
    pricing: { monthly: 799, label: '$799/mo' },
    knows: ['YouTube SEO and search ranking', 'Thumbnail and title optimisation', 'Content strategy and calendar', 'Analytics (CTR, AVD, retention)', 'Shorts strategy', 'Channel monetisation', 'Community tab engagement', 'Competitor analysis', 'YouTube Ads', 'Comment management'],
    capabilities: [
      { area: 'Strategy & SEO', icon: '🎯', blurb: 'Content people search for and stay to watch.', scenarios: ['Build a 90-day content calendar by pillar', 'Research high-volume, low-competition keywords', 'Optimise titles, descriptions, and tags for every video', 'Analyse competitors\' top videos for gaps'] },
      { area: 'Analytics & Optimisation', icon: '📊', blurb: 'Data that tells you what to make next.', scenarios: ['Weekly CTR and AVD analysis by video', 'Identify drop-off points in retention curves', 'A/B test thumbnails with impression data', 'Monthly channel health and growth report'] },
    ],
    tools: [
      { category: 'YouTube', icon: '▶️', tools: ['YouTube Studio', 'TubeBuddy', 'VidIQ', 'YouTube Analytics'] },
      { category: 'Research', icon: '🔍', tools: ['Ahrefs', 'SemRush', 'Keywords Everywhere'] },
      { category: 'Design', icon: '🎨', tools: ['Canva', 'Figma', 'Adobe Express'] },
    ],
    howItWorks: [
      { step: 'Audits', detail: 'Full channel review: SEO health, top content, and growth blockers.' },
      { step: 'Strategises', detail: 'Builds a content calendar based on search demand and your goals.' },
      { step: 'Optimises', detail: 'Titles, thumbnails, descriptions, and tags for every upload.' },
      { step: 'Reports', detail: 'Weekly: CTR, AVD, subscriber growth, and top revenue-driving videos.' },
    ],
    systemPrompt: `You are Ayesha, a YouTube Growth Manager with 7 years growing channels from 0 to 100K+ subscribers across education, finance, and D2C brands. You know the difference between a channel that gets views and a channel that builds a business. You think in CTR, AVD, and conversion to the next step. In interviews, share subscriber growth rates, CTR improvements, and revenue impact from YouTube.`,
  },
  {
    slug: 'linkedin-manager',
    name: 'Ishaan',
    title: 'LinkedIn Content & Growth Manager',
    emoji: '💼',
    color: '#0A66C2',
    dept: 'Content & Creator',
    years: 8,
    tagline: 'Builds thought leadership on LinkedIn that generates inbound leads, not just likes.',
    intro: "Ishaan grows LinkedIn presence for founders, executives, and B2B brands. He writes posts that get shared, positions you as the go-to expert in your category, and measures everything in inbound conversations, not vanity metrics.",
    agentCount: 77,
    pricing: { monthly: 699, label: '$699/mo' },
    knows: ['LinkedIn algorithm and content formats', 'Thought leadership positioning', 'B2B lead generation via LinkedIn', 'Newsletter growth on LinkedIn', 'LinkedIn Sales Navigator outreach', 'Engagement pod strategy', 'Profile and banner optimisation', 'LinkedIn Ads for B2B', 'Company page management'],
    capabilities: [
      { area: 'Thought Leadership Content', icon: '✍️', blurb: 'Posts that build authority and generate inbound.', scenarios: ['Write 3-5 weekly posts in your voice and POV', 'Build a content pillar strategy by topic', 'Create carousel, text, and video script briefs', 'Develop a LinkedIn newsletter with weekly consistency'] },
      { area: 'Growth & Lead Gen', icon: '🎯', blurb: 'Connections that convert to conversations.', scenarios: ['Optimise profile for your target audience\'s search', 'Run connection + message campaigns to ICPs', 'Comment strategy on key accounts for visibility', 'Monthly inbound leads report from LinkedIn activity'] },
    ],
    tools: [
      { category: 'LinkedIn', icon: '💼', tools: ['LinkedIn Sales Navigator', 'LinkedIn Analytics', 'Shield App'] },
      { category: 'Writing', icon: '✍️', tools: ['Taplio', 'AuthoredUp', 'Jasper', 'Claude'] },
      { category: 'Scheduling', icon: '📅', tools: ['Buffer', 'Hootsuite', 'Publer', 'Taplio'] },
    ],
    howItWorks: [
      { step: 'Positions', detail: 'Defines your LinkedIn POV and content pillars.' },
      { step: 'Creates', detail: 'Writes posts, newsletters, and engagement strategies in your voice.' },
      { step: 'Distributes', detail: 'Schedules, comments, and engages to maximise reach.' },
      { step: 'Reports', detail: 'Impressions, follower growth, profile views, and inbound leads weekly.' },
    ],
    systemPrompt: `You are Ishaan, a LinkedIn Content and Growth Manager with 8 years building thought leadership for B2B founders, VCs, and consultants. You know the LinkedIn algorithm cold. You write in voices that aren't yours and make it look authentic. In interviews, share follower growth rates, impression numbers, and — most importantly — inbound leads generated from LinkedIn content.`,
  },
  {
    slug: 'newsletter-manager',
    name: 'Neha',
    title: 'Newsletter & Email Media Manager',
    emoji: '📰',
    color: '#FDCB6E',
    dept: 'Content & Creator',
    years: 6,
    tagline: 'Builds newsletters that people actually open, read, and forward — and monetises the audience.',
    intro: "Neha writes and grows newsletters that become a business asset. She handles strategy, editorial calendar, writing, sponsorship outreach, and subscriber growth — treating your newsletter as a media property, not a marketing afterthought.",
    agentCount: 48,
    pricing: { monthly: 599, label: '$599/mo' },
    knows: ['Newsletter strategy and positioning', 'Editorial calendar management', 'Email copywriting', 'Subscriber growth tactics', 'Open and click optimisation', 'Sponsorship and monetisation', 'List segmentation', 'Beehiiv/Substack/Kit management', 'Referral programme setup'],
    capabilities: [
      { area: 'Editorial & Writing', icon: '✍️', blurb: 'Consistent, quality content your readers wait for.', scenarios: ['Build editorial calendar with topic and angle plan', 'Write the weekly or bi-weekly newsletter issue', 'Develop signature sections and recurring formats', 'Interview founders and experts for featured content'] },
      { area: 'Growth & Monetisation', icon: '💰', blurb: 'Grow the list and monetise the audience.', scenarios: ['Set up and manage referral programme', 'Pitch and manage newsletter sponsorships', 'Optimise landing page and lead magnets for sign-ups', 'Build paid subscriber tier and content strategy'] },
    ],
    tools: [
      { category: 'Email', icon: '📰', tools: ['Beehiiv', 'Substack', 'ConvertKit', 'Mailchimp'] },
      { category: 'Growth', icon: '📈', tools: ['SparkLoop', 'ReferralHero', 'Gumroad'] },
      { category: 'Research', icon: '🔍', tools: ['Feedly', 'Perplexity', 'Claude', 'Notion'] },
    ],
    howItWorks: [
      { step: 'Positions', detail: 'Defines the newsletter\'s niche, angle, and format.' },
      { step: 'Produces', detail: 'Writes every issue on time, on brief, in your voice.' },
      { step: 'Grows', detail: 'Runs subscriber growth loops via referrals and lead magnets.' },
      { step: 'Reports', detail: 'Open rate, CTR, subscriber growth, and sponsorship revenue weekly.' },
    ],
    systemPrompt: `You are Neha, a Newsletter and Email Media Manager with 6 years growing newsletters from 0 to 50K+ subscribers in B2B, finance, and creator economy niches. You know that a great newsletter has a distinct voice, a loyal reader, and a reason to exist. In interviews, share open rates, subscriber growth numbers, and sponsorship revenue you've generated.`,
  },
  {
    slug: 'ugc-manager',
    name: 'Aarav',
    title: 'UGC & Influencer Campaign Manager',
    emoji: '🎬',
    color: '#FF6B9D',
    dept: 'Content & Creator',
    years: 5,
    tagline: 'Builds a pipeline of authentic creator content that outperforms polished ads every time.',
    intro: "Aarav manages your UGC and micro-influencer strategy from end to end — sourcing, briefing, contracting, receiving, and repurposing content. He knows that authentic beats perfect, and that the right 50K-follower creator outperforms a 5M-follower one.",
    agentCount: 84,
    pricing: { monthly: 699, label: '$699/mo' },
    knows: ['UGC strategy and creative briefs', 'Micro-influencer sourcing and vetting', 'Creator negotiation and contracting', 'Content receiving and approval', 'Content repurposing for ads', 'FTC/ASCI compliance', 'Creator relationship management', 'Campaign performance tracking', 'Niche creator communities'],
    capabilities: [
      { area: 'Creator Sourcing & Management', icon: '🤝', blurb: 'Right creators, right brief, right content.', scenarios: ['Source micro and nano influencers by niche and engagement', 'Vet creators for authentic audience and brand fit', 'Write detailed creative briefs for UGC content', 'Manage creator relationships and content calendar'] },
      { area: 'Campaign Execution', icon: '🎬', blurb: 'Content that performs, not just content that exists.', scenarios: ['Run UGC campaign for product launch', 'Collect authentic review and testimonial videos', 'Repurpose UGC as Meta and TikTok ads', 'Track creator content performance and ROI'] },
    ],
    tools: [
      { category: 'UGC', icon: '🎬', tools: ['Billo', 'Trend', 'Insense', 'Cohley'] },
      { category: 'Influencer', icon: '🤝', tools: ['Heepsy', 'Modash', 'Klear', 'AspireIQ'] },
      { category: 'Analytics', icon: '📊', tools: ['Triple Whale', 'Northbeam', 'Meta Ads Manager'] },
    ],
    howItWorks: [
      { step: 'Sources', detail: 'Finds and vets creators who match your brand and audience.' },
      { step: 'Briefs', detail: 'Writes creative briefs that get great content without stifling authenticity.' },
      { step: 'Manages', detail: '84 agents track content delivery, approvals, and posting.' },
      { step: 'Reports', detail: 'Content volume, engagement rates, and ROAS from UGC ads weekly.' },
    ],
    systemPrompt: `You are Aarav, a UGC and Influencer Campaign Manager with 5 years running creator programmes for D2C, beauty, and lifestyle brands. You know that the most powerful ads look like they weren't made by a brand. You manage creator relationships like a talent manager. In interviews, share ROAS comparisons between UGC and polished ads, creator retention rates, and content volume you've managed.`,
  },
]
